### ISSUE TITLE
make doesn't use installed OpenBLAS

### ISSUE THREAD

**Issue by GrapeJamMan** [Ultimaker/cura-build#104]
I saw build instructions for Linux so I took a stab at getting this done on Raspbian. So far this has been a really painful process that also required me to build Python 3.5.2, SIP, and modify URLs for QT, and I hit an error (below) because it tries to compile OpenBLAS targeting an x86 platform instead of ARM.

But, this is not an OpenBLAS problem. I was able to download, compile, and install from their source with their make files. Something in cura-build is either forcing a different platform from mine or simply isn't checking whether it's already installed.

Output is below, any ideas or is are there extra steps I need to take? 

dynamic.c: In function ‘support_avx’:
dynamic.c:107:3: warning: implicit declaration of function ‘cpuid’ [-Wimplicit-function-declaration]
   cpuid(1, &eax, &ebx, &ecx, &edx);
   ^
dynamic.c:97:3: error: impossible constraint in ‘asm’
   __asm__ __volatile__
   ^
Makefile:83: recipe for target 'dynamic.o' failed
make[4]: *** [dynamic.o] Error 1
make[4]: *** Waiting for unfinished jobs....
Makefile:143: recipe for target 'libs' failed
make[3]: *** [libs] Error 1
CMakeFiles/OpenBLAS.dir/build.make:113: recipe for target 'OpenBLAS-prefix/src/OpenBLAS-stamp/OpenBLAS-build' failed
make[2]: *** [OpenBLAS-prefix/src/OpenBLAS-stamp/OpenBLAS-build] Error 2
CMakeFiles/Makefile2:292: recipe for target 'CMakeFiles/OpenBLAS.dir/all' failed
make[1]: *** [CMakeFiles/OpenBLAS.dir/all] Error 2
Makefile:105: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Ghostkeeper** [comment]
We use `DYNAMIC_ARCH=1` and `NO_STATIC=1` to compile OpenBLAS. These are required for our normal Cura builds.

**Comment by LipuFei** [comment]
Closing this ticket due to inactivity.
