### ISSUE TITLE
Cura build error on Windows 10: No module named 'Arcus'

### ISSUE THREAD

**Issue by maarstra** [Ultimaker/cura-build#106]
When building cura on Windows 10 using mingw32-make, I get the following error

...
Copying NSIS scripts
Running cx_Freeze
Traceback (most recent call last):
  File "setup_win32.py", line 14, in <module>
    import Arcus
ImportError: No module named 'Arcus'
CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
mingw32-make[2]: *** [build_exe] Error 1
CMakeFiles\Makefile2:600: recipe for target 'CMakeFiles/build_exe.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by maarstra** [comment]
Import problem solved by the following steps:

1. Either edit setup_win32.py and simply change 'Arcus' to arcus or modify the Arcus installation folder to 'Arcus'

**Comment by Ghostkeeper** [comment]
@awhiemstra Should we incorporate this change to our set-up script?

**Comment by awhiemstra** [comment]
I'm not sure why it is producing a lower-case Arcus in the first place. On my machine, the built file is called Arcus.pyd. I am also working on an updated build system for Windows, so I am rather hesitant to touch this at the moment.
