### ISSUE TITLE
Uranium build issue

### ISSUE THREAD

**Issue by greysAcademicCode** [Ultimaker/cura-build#11]
When I run the ubuntu build script I get this warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_SITE_PACKAGES_DIR
    URANIUM_PLUGINS_DIR
```
It seems that when the build script tries to override the defaults for these CMake variables, it doesn't work and things get installed in the wrong places.

**Comment by awhiemstra** [comment]
As far as I know this is working properly for 15.10. Please reopen if it is still an issue.
