### ISSUE TITLE
sip question on win10

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/cura-build#113]
if i install pyqt in this way PyQt5-5.6-gpl-Py3.5-Qt5.6.0-x32-2.exe
do i still need to install the sip separetely?
could anyone help me on that? thanks

**Comment by sedwards2009** [comment]
I don't know. You need to see if there is a file `sip.exe` somewhere in the all the stuff it installs. I know that Riverbank Computing has stopped producing windows installers for PyQt. Instead they provide python wheels which can be installed via `pip`. These wheels do not include `sip.exe`.

(Also, that exe appears to be a 32bit version too which you might not want. 64bit is preferred.)

**Comment by LipuFei** [comment]
@sedwards2009 has given a sufficient answer. I'll close this issue.
