### ISSUE TITLE
Libarcus not listed as dependency in readme build instructions

### ISSUE THREAD

**Issue by djhenjin** [Ultimaker/cura-build#117]
on the readme.md the build deps are missing libarcus. this leads to a failed build.

Solution:
Add libarcus to the dependencies list in the readme.md file to alleviate build issues
EDIT: the dependencies lists Arcus, however libarcus is the needed part to install.

**Comment by gregoryleblanc** [comment]
David posted this after trying to help me out on IRC yesterday.  

After some more reading, I'm not clear on whether libarcus should be installed before using cura-build, or if cura-build should build it as part of its process.

cura-build output: http://pastebin.com/8mrnN9EG
CMakeOutput.log http://pastebin.com/XfdUy9rf

**Comment by Ghostkeeper** [comment]
It should either be part of cura-build-environment (building the dependencies of Cura) or of cura-build. I was under the impression that it would be part of the environment, e.g. a dependency rather than part of the main program. Perhaps @awhiemstra can provide clarity there.

**Comment by awhiemstra** [comment]
It is part of the environment, both because I want to decouple Arcus from main Cura releases and because on Windows it needs to be built with MSVC. I simply have not really got around to updating the cura-build documentation.

**Comment by LipuFei** [comment]
I've just checked the README and libArcus got included at some point. I'll close this ticket.
