### ISSUE TITLE
 Could NOT find PyQt

### ISSUE THREAD

**Issue by chintanjosh** [Ultimaker/cura-build#122]
I am using Ubuntu 14.04
I followed this steps
cloned this repo

`mkdir build && cd build`
`cmake ..`
it gives me this error

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'PyQt5'
CMake Error at /home/xyz/Downloads/cmake-3.7.2-Linux-x86_64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PyQt: Found unsuitable version "", but required is at least
  "5.6" (found )
`

I do have the PyQt installed in my system
I checked it through 
python3
import PyQt5

is there any path that is to be set ?

**Comment by Ghostkeeper** [comment]
Did you find a solution?

**Comment by chintanjosh** [comment]
No, I installed all the dependencies step by step, and then ran cura_app.py from Cura, which worked.
But this error still stays. I tried to delete this but didn't found any option and hence closed it, as I feel that this is some mistake from my part.
