### ISSUE TITLE
When will cura-build-2.6 release？ && have build problem

### ISSUE THREAD

**Issue by MacroHu** [Ultimaker/cura-build#127]
I just find some incredible function like multi-exturder printing in Cura V2.6, so I decide to debug Cura-2.6 GUI in IDE , and I use Eclipse+pydev in Ubuntu 16.04. But all trying were failed, because of the dependency problem, I have tried follows:

1.**Build single Cura-2.6 project** ,but dependency problems comes out one by one. When I fix the " ImportError: No module named 'UM' " by **sys.path.append(where i clone and build Uranium)**(PS: I don't know why the method set PYTHONPATH didn't work), then Arcus problem happened..., so i copy libArucs build folder which include all .so file into Cura-2.6 folder and change it's name to Arcus.Then the problem turns to "Arcus not attributes to Socket", I haven't fix it till now.

2.**Use cura-build-environment to fix the dependency**,but not find version 2.6. I another version like 2.5 I tried also failed when  I **make** it. 

I have follow all the steps in readme file, is my ubuntu system has problem？Does someone build it successful？

And when will cura-build-2.6  release？

**Comment by nallath** [comment]
Building it is only a thing if you want to make appimages or executables. If you just want to run from source, you don't need this repo.

**Comment by Ghostkeeper** [comment]
> 2.Use cura-build-environment to fix the dependency,but not find version 2.6.

I've tagged the 2.6.0 releases on cura-build and cura-build-environment now. Nothing has changed since its release.

**Comment by ChrisRiddell** [comment]
@nallath is there any documentation on just running Cura master from source (on windows or osx)?

**Comment by nallath** [comment]
Checkout Cura, Uranium, CuraEngine, LibArcus.
1. Build LibArcus 
2. Build Cura engine
3. Ensure Uranium is in your pythonpath.
4. Run cura_app.py with python3 
5. If complaining about dependencies, install those with pip.

That's pretty much how i recently installed my new laptop.

**Comment by MacroHu** [comment]
@nallath Thks, I will follow these steps and try it again.

**Comment by MacroHu** [comment]
@Ghostkeeper Thanks a lot.

**Comment by Ghostkeeper** [comment]
I'd like to preface Nallath's steps with: 0. Build Protobuf. It's still hard to get a pre-built version of that.

**Comment by ChrisRiddell** [comment]
@nallath I followed your instructions on Ubuntu 17.10 and when it started to load the interface it crashes  with this :/ I installed the complaining dependencies with pip3 

> Current thread 0x00007f4f0a4f5740 (most recent call first):
>   File "/home/chris/Desktop/Test/Uranium/UM/Qt/QtApplication.py", line 237 in initializeEngine
>   File "/home/chris/Desktop/Test/Cura/cura/CuraApplication.py", line 713 in run
>   File "cura_app.py", line 83 in <module>
> Segmentation fault (core dumped)

**Comment by Ghostkeeper** [comment]
Ubuntu 17.10 comes with Python 3.6, so if you still have binaries for Python 3.5 you might get that crash.

Otherwise I'd run `gdb --args python3 cura_app.py` to get a stack trace of what's causing that segfault. A stack trace should indicate at least in what library the fault occurs.

**Comment by ChrisRiddell** [comment]
@Ghostkeeper 

I get the following running that command 

> $ gdb --args python3 cura_app.py
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from /usr/lib/debug/.build-id/62/f45a63637adfb24578bf094814d28eb0cf8309.debug...done.
done.

Now if i run the python3 cura_app.py it just seg faults right away but I do get a crash popup from Ubuntu saying python3.6 crashed with the following

> python3 crashed with SIGSEGV in unicode_fromformat_write_cstr()

It seems to happen after I finish installing the dependency's it complains about using pip3 the last been pyqt

**Comment by Ghostkeeper** [comment]
> Now if i run the python3 cura_app.py it just seg faults right away but I do get a crash popup from Ubuntu

Strange. Normally GDB should catch that segfault and display it when you give the `bt` command... Your error message says nothing to me. I didn't even know about that `/usr/lib/debug/.build-id` folder.

> I also had to cp /usr/local/lib/python3/dist-packages/Arcus.so to /usr/local/lib/python3.6/dist-packages as it could not find arcus other wise

You will need to re-compile libArcus against Python 3.6 since the binary interfaces of Python 3.5 and 3.6 aren't compatible. I had to do that as well when I updated Ubuntu to 17.10 (so if you like I can provide a binary build that I made on my work laptop against Python 3.6).

**Comment by ChrisRiddell** [comment]
@Ghostkeeper  One question how do you build libArcus against Python 3.6 is their a flag I need to add to the cmake or make command?

**Comment by Ghostkeeper** [comment]
I don't think there was anything special to it. I think I just changed the install prefix and left the rest intact. Be sure to rebuild Protobuf first though!

These are the CMake parameters I'm using right now:

    BUILD_EXAMPLES: ON
    BUILD_PYTHON: ON
    BUILD_STATIC: OFF
    CMAKE_BUILD_TYPE: Debug
    CMAKE_INSTALL_PREFIX: /home/ruben/dev/inst
    MSVC_STATIC_RUNTIME: OFF
    PYTHON_SITE_PACKAGES_DIR: lib/python3/dist-packages
    _find_sip_py: /home/ruben/Projects/libArcus/cmake/FindSIP.py
    protobuf_MODULE_COMPATIBLE: ON
