### ISSUE TITLE
get_filename_component unknown component CACHE error in building Cura-2.6.0

### ISSUE THREAD

**Issue by MacroHu** [Ultimaker/cura-build#131]
Hi guys, I got some problems in building Cura-2.6.0, things many of you may had ever met.

I am trying to build cura-2.6.0 to .deb package in Ubuntu16.04-desktop-amd64, these are my steps.

Step1: Use cura-build-environment-2.6.0 to install the dependencies of cura-2.6.0.

Step2: Use cura-build-2.6.0 to build cura-2.6.0.

I have fixed up the build errors of cura-build-environment-2.6.0 and finished step1.

[ 6%] Built target Python
[ 12%] Built target PySerial
[ 17%] Built target PythonNetifaces
[ 23%] Built target Qt
[ 28%] Built target Sip
[ 33%] Built target PyQt
[ 38%] Built target AppImageKit
[ 43%] Built target OpenBLAS
[ 48%] Built target NumPy
[ 54%] Built target SciPy
[ 60%] Built target python-utils
[ 66%] Built target NumpySTL
[ 72%] Built target Protobuf
[ 78%] Built target Arcus
[ 84%] Built target PythonSix
[ 89%] Built target PythonZeroconf
[ 10%] Built target pugixml
[ 94%] Built target Savitar
[100%] Built target cx_Freeze
[100%] Built target projects

My cmake command of cura-build-environment-2.6.0：

cmake .. -DCMAKE_INSTALL_PREFIX=/0-A/Install_Dir_Cura-Build-Environment-2.6.0 -DCMAKE_BUILD_TYPE=Release
Quote from ~/cura-build-environment-2.6.0/README.md:
<<<<<<<<<<<<<<<<<<
The end result of this project should be a complete build environment
installed to CMAKE_INSTALL_PREFIX. This environment can be used in
combination with the [cura-build] repository to produce Cura executables for
all three supported platforms.

So I try the same CMAKE_INSTALL_PREFIX to build cura-build-2.6.0 but failed.
<<<<<<<<<<<<<<
root@yue-virtual-machine:/0-A/Package/cura-build-2.6.0/build# cmake .. -DCMAKE_INSTALL_PREFIX=/0-A/Install_Dir_Cura-Build-Environment-2.6.0
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:23 (get_filename_component):
get_filename_component unknown component CACHE

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protobuf: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/libprotobuf.a (Required is at least version "3.0.0")
-- Found PythonInterp: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5.0")
-- Found PyQt: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/PyQt5 (found suitable version "5.8.2", minimum required is "5.6")
-- Found SciPy: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/scipy (found suitable version "0.17.1", minimum required is "0.17")
-- Found cx_Freeze: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/cx_Freeze (found suitable version "5.0", minimum required is "5.0")
-- Found AppImageKit: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/bin/AppImageAssistant
-- Found GPG: /usr/bin/gpg
-- Found SHA1Sum: /usr/bin/sha1sum
-- Configuring incomplete, errors occurred!
See also "/0-A/Package/cura-build-2.6.0/build/CMakeFiles/CMakeOutput.log".
See also "/0-A/Package/cura-build-2.6.0/build/CMakeFiles/CMakeError.log".
root@yue-virtual-machine:/0-A/Package/cura-build-2.6.0/build#

  **get_filename_component unknown component CACHE**
I can't fix this CACHE error in CmakeList.txt ↑

target info in CmakeList.txt
<<<<<<
//# This should care that our CMAKE_PREFIX_PATH is absolute at the end...
get_filename_component(CMAKE_PREFIX_PATH
${CMAKE_PREFIX_PATH}
ABSOLUTE
CACHE FORCE)

Do somebody know how to fix it? And most importantly，Is that my method to combine cura-build-environment-2.6.0 with cura-build-2.6.0 wrong?
How to combine cura-build-environment-2.6.0 with cura-build-2.6.0 ??

**Comment by awhiemstra** [comment]
The error is produced because the cura-build CMake file currently naively assumes you always set CMAKE_PREFIX_PATH. This variable is used by CMake to search for dependencies and is how we tie cura-build and cura-build-environment together. Since you were using cura-build-environment, you can set CMAKE_PREFIX_PATH to cura-build-environment's CMAKE_INSTALL_PREFIX and everything should work.

**Comment by woshisuchao** [comment]
i use your methor result this problem,thank you ,and i also have got a warnning

**Comment by woshisuchao** [comment]
i use your methor result this problem,thank you ,and i also have got a warnning

**Comment by woshisuchao** [comment]
cmake -G "MinGW Makefiles" -DBUILD_64BIT:BOOL=ON -DSIGN_PACKAGE:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../../curaexe  -DCMAKE_PREFIX_PATH=../../curaexe ..

and i folow next step :mingw32-make.
but rise this problem
collect2.exe: error: ld returned 1 exit status
mingw32-make[5]: *** [CMakeFiles\CuraEngine.dir\build.make:119: CuraEngine.exe] Error 1
mingw32-make[4]: *** [CMakeFiles\Makefile2:142: CMakeFiles/CuraEngine.dir/all] Error 2
mingw32-make[3]: *** [Makefile:151: all] Error 2
mingw32-make[2]: *** [CMakeFiles\CuraEngine.dir\build.make:110: CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:253: CMakeFiles/CuraEngine.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

**Comment by woshisuchao** [comment]
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@D_K@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DN@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DO@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBX@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0xc): undefined reference to `__std_terminate'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x24): undefined reference to `__std_terminate'

**Comment by woshisuchao** [comment]
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@D_K@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DN@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DO@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBX@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0xc): undefined reference to `__std_terminate'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x24): undefined reference to `__std_terminate'

**Comment by woshisuchao** [comment]
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@D_K@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DN@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DO@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBX@Z]+0x10): undefined reference to `__GSHandlerCheck'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x1c): undefined reference to `__GSHandlerCheck_EH'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0xc): undefined reference to `__std_terminate'
H:/cura/install/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/H_/cura/protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$stateUnwindMap$?_Fput@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@AEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DPEBD_K@Z]+0x24): undefined reference to `__std_terminate'

**Comment by Ghostkeeper** [comment]
Did you compile libProtobuf using the same compiler as libArcus and CuraEngine?
