### ISSUE TITLE
Slicing engine for Cura stop working 

### ISSUE THREAD

**Issue by woshisuchao** [Ultimaker/cura-build#169]
when i succeed building the cura-build and install over cura, but when i run the app , Slicing engine for Cura stop working . 
then i use command to test curaengine 
like that

H:\Program Files\Ultimaker Cura 0.0>curaengine slice  -v -j ./ultimaker2.def.json -o "output.gcode" -e1 -s infill_line_distance=0 -e0 -l "test.stl"

Cura_SteamEngine version 0.0.0
Copyright (C) 2018 Ultimaker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
Loading ./ultimaker2.def.json...
Loading H:\Program Files\Ultimaker Cura 0.0\resources\definitions/ultimaker.def.json...
Loading H:\Program Files\Ultimaker Cura 0.0\resources\definitions/fdmprinter.def.json...
[ERROR] Failed to open output.gcode for output.

**Comment by woshisuchao** [comment]
'CuraEngine.exe' (Win32): Loaded 'H:\Program Files\Ultimaker Cura 0.0\CuraEngine.exe'. Module was built without symbols.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\ntdll.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\kernel32.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\KernelBase.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\msvcrt.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Program Files\Ultimaker Cura 0.0\libgcc_s_seh-1.dll'. Module was built without symbols.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\user32.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\gdi32.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Program Files\Ultimaker Cura 0.0\libwinpthread-1.dll'. Module was built without symbols.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\ws2_32.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\sechost.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\nsi.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Program Files\Ultimaker Cura 0.0\libstdc++-6.dll'. Module was built without symbols.
'CuraEngine.exe' (Win32): Loaded 'H:\Program Files\Ultimaker Cura 0.0\libgomp-1.dll'. Module was built without symbols.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\imm32.dll'. Symbols loaded.
'CuraEngine.exe' (Win32): Loaded 'H:\Windows\System32\msctf.dll'. Symbols loaded.
The thread 0x6a0 has exited with code 1 (0x1).
The thread 0x2564 has exited with code 1 (0x1).
The thread 0x25fc has exited with code 1 (0x1).
The program '[12144] CuraEngine.exe' has exited with code 1 (0x1).

**Comment by Ghostkeeper** [comment]
The test you're running is invalid. You specified an `output.gcode` file where it should print the output but CuraEngine can't open that, because you're running it from Program Files where it would need administrator rights to write.
