### ISSUE TITLE
about cmake

### ISSUE THREAD

**Issue by woshisuchao** [Ultimaker/cura-build#170]
I recently bulit a 3Dslice excution called cura.
Cura-build
Cura
    /cura-build-enviroment
    /curaenv
I build the enviroment in curaenv using "cmake .. -DCMAKE_INSTALL_PREFIX=.../curaenv -DCMAKE_BUILD_TYPE=Release ^
   -G "NMake Makefiles"   "
then build the curaengine in cura-build/build like this
"cmake -G "MinGW Makefiles" -DBUILD_64BIT:BOOL=ON -DSIGN_PACKAGE:BOOL=OFF -DCMAKE_INSTALL_PREFIX=./  -DCMAKE_PREFIX_PATH=../../cura/curaenv .."
but when i run the excution, the slice engine cant work.
then i use command to test curaengine like that

H:\Program Files\Ultimaker Cura 0.0>curaengine slice -v -j ./ultimaker2.def.json -o "output.gcode" -e1 -s infill_line_distance=0 -e0 -l "test.stl"

Cura_SteamEngine version 0.0.0
 Copyright (C) 2018 Ultimaker

This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
 along with this program. If not, see http://www.gnu.org/licenses/.
 Loading ./ultimaker2.def.json...
 Loading H:\Program Files\Ultimaker Cura 0.0\resources\definitions/ultimaker.def.json...
 Loading H:\Program Files\Ultimaker Cura 0.0\resources\definitions/fdmprinter.def.json...
 [ERROR] Failed to open output.gcode for output.

is there any problem?

and if i change some prefix  it will enven not succeed.

for example 
cura-build
              /build
              /cura-build-enviroment
in the cura-build-enviroment/build:
cmake .. -DCMAKE_INSTALL_PREFIX=./ -DCMAKE_BUILD_TYPE=Release ^
   -G "NMake Makefiles"
then 
in the cura-build/build
cmake -G "MinGW Makefiles" -DBUILD_64BIT:BOOL=ON -DSIGN_PACKAGE:BOOL=OFF -DCMAKE_INSTALL_PREFIX=./  -DCMAKE_PREFIX_PATH=../cura-build-enviroment/build ..

**Comment by nallath** [comment]
This seems to be a permission error.

**Comment by woshisuchao** [comment]
2018-02-24 09:14:05,071 - ERROR - [(8396)-MainThread] UM.Backend.Backend._runEngineProcess [141]: Couldn't start back-end: No permission to execute process

yeh , indeed the log do such state, but how can i result it.. thankyou --i am hand

**Comment by woshisuchao** [comment]
2018-02-24 09:14:05,071 - ERROR - [(8396)-MainThread] UM.Backend.Backend._runEngineProcess [141]: Couldn't start back-end: No permission to execute process

yeh , indeed the log do such state, but how can i result it.. thankyou --i am new hand
@nallath

**Comment by Ghostkeeper** [comment]
You are currently using this command to slice:

    H:\Program Files\Ultimaker Cura 0.0>curaengine slice -v -j ./ultimaker2.def.json -o "output.gcode" -e1 -s infill_line_distance=0 -e0 -l "test.stl"

That `-o "output.gcode"` says that it must write the g-code file to the file "output.gcode" in your current directory. Your current directory is `H:\Program Files\Ultimaker Cura 0.0`, which is in your Program Files and so requires administrative rights to write to.

Instead, try something like this:

    H:\Program Files\Ultimaker Cura 0.0>curaengine slice -v -j ./ultimaker2.def.json -o "H:\output.gcode" -e1 -s infill_line_distance=0 -e0 -l "test.stl"

This will write the output to the root `H:` directory where it's more likely to be allowed.
