### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by yzy65172846** [Ultimaker/cura-build#179]
I build cura but it can't work.
![image](https://user-images.githubusercontent.com/37525539/39902545-20f7e45e-5501-11e8-8b51-ec182ff5cc75.png)

How can I find what dll is failed？
I use the Python3.5.4 with the newest module to package cura.

**Comment by Ghostkeeper** [comment]
What does the Chinese text say?

**Comment by Ghostkeeper** [comment]
Make sure that the DLLs are compiled using the same compiler as whatever is calling them. This means that if you're dynamically linking libArcus to CuraEngine, libArcus needs to be compiled with the same compiler as CuraEngine (i.e. MinGW). And all Python modules need to be compiled with the same compiler as CPython (i.e. MSVC). In particular for libArcus and Protobuf, this means that you'll have to compile them twice, once with MinGW and once with MSVC.

**Comment by Ghostkeeper** [comment]
You can also try to use [Dependency Walker](http://www.dependencywalker.com/) to find out which DLLs are broken.

**Comment by LipuFei** [comment]
It has been almost 4 months without response. I will close this then.
