### ISSUE TITLE
packaging error import bz2

### ISSUE THREAD

**Issue by mirondius** [Ultimaker/cura-build#181]
Hi all,
I build successfully the build env provided in the other git.
Also successfully linked the build process to the build env.
But getting following error:
```
Traceback (most recent call last):
  File "/tmp/.mount_YNI1iS/AppImageAssistant", line 44, in <module>
    import bz2
ImportError: No module named bz2
CMakeFiles/packaging.dir/build.make:61: recipe for target 'packaging' failed
make[2]: *** [packaging] Error 1
CMakeFiles/Makefile2:332: recipe for target 'CMakeFiles/packaging.dir/all' failed
make[1]: *** [CMakeFiles/packaging.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I linked AppImageAssistant to the build env:
CMakeCache.txt
```
//Path to a program.
APPIMAGEKIT_APPRUN_EXECUTABLE:FILEPATH=/home/XXX/cura/cura-environment/bin/AppRun

//Path to a program.
APPIMAGEKIT_ASSISTANT_EXECUTABLE:FILEPATH=/home/XXX/cura/cura-environment/bin/AppImageAssistant
```
And also python3.5 is linked to the build env:
```
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/home/XXX/cura/cura-environment/bin/python3.5
```

As I understood the error from other sites, this error occurs only, when python has no libbz2 installed. So I went to cura-environment/lib/python3.5/ and there is bz2.py available.
With best regards
mirondius

**Comment by mirondius** [comment]
Weird now:
It seems, that with the make process, my python is used, insteed of the python of the build env. Also not python3, but python2. So I justed used as a workaround and linked my python2 binaries to python3. Now I get:
```
  File "/tmp/.mount_AMExs2/AppImageAssistant", line 52
    print "Usage:"
                 ^
SyntaxError: Missing parentheses in call to 'print'
CMakeFiles/packaging.dir/build.make:61: recipe for target 'packaging' failed
make[2]: *** [packaging] Error 1
CMakeFiles/Makefile2:332: recipe for target 'CMakeFiles/packaging.dir/all' failed
make[1]: *** [CMakeFiles/packaging.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Obviously it is using my python, but why and where is the variable in the make files for using my python insteed of the build env?

**Comment by Ghostkeeper** [comment]
That is very weird, since `bz2` is a built-in module in Python since version 2.3.

You should be able to choose your Python environment using the `PYTHON_EXECUTABLE` variable in CMake for cura-build. It is normally found automatically via FindPythonInterp.

**Comment by LipuFei** [comment]
Hi @mirondius , in order to get the `bz2` module in python, you need to have the `bz2` library for development. Otherwise, during python's configuration phrase, if it cannot find `bz2`, it won't compile the `bz2` package in python. The same holds for many other packages such as `lzma`, `ssl`, `sqlite`, etc.

**Comment by LipuFei** [comment]
Note that you need to underlying `libbz2` to compile the `bz2` module in python. `libbz2` is not intentionally included in our system, so you may not have the `bz2` python module after you compile and install `cura-build-environment`. I think we should include it because it's kinda a builtin module.

**Comment by LipuFei** [comment]
`libbzip2` is now included in the cura-build-environment as a dependency so the `bz2` module in python will be built. Check this commit for more details https://github.com/Ultimaker/cura-build-environment/commit/7303f30eed4fa3b546da3cf84556392502d98d9d

I'll close this issue.
