### ISSUE TITLE
missing dependency list for linux/ubuntu build

### ISSUE THREAD

**Issue by sk8nfool** [Ultimaker/cura-build#182]
The dependency list is empty for the linux/ubuntu build.
I tried to let CMake tell me what was missing by repeatedly running and installing what it tripped over. This got me to install

libarcus-dev
libprotobuf-dev
qtbase5-dev
qtdeclarative5-dev

And then I ran into trouble when cmake couldn't find cs_freeze. What really needs to be done is a complete list of dependencies and how to install them be added to the instructions. I'm not a python literate person so this is a non-trivial task.

**Comment by Amppa** [comment]
try  pip3 install cx_Freeze

**Comment by thopiekar** [comment]
I don't recommend that.
First there is cxfreeze in Ubuntu's repos and second cxfreeze is provided by cura-build-environment.

**Comment by Ghostkeeper** [comment]
These dependencies should get installed by installing the [cura-build-environment](https://github.com/Ultimaker/cura-build-environment) project. I've documented this here: https://github.com/Ultimaker/cura-build/commit/1c4f6712f92fea4f0926088b3e8a37c3d895f806
