### ISSUE TITLE
OSX: Homebrew geos version 3.6.3

### ISSUE THREAD

**Issue by plasticlobster** [Ultimaker/cura-build#188]
The packaging scripts for OSX appear to be explicitly dependent on the homebrew-installed  /usr/local/Cellar/geos/3.6.2 library files. Homebrew updated geos to 3.6.3:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/geos.rb

As a result, new attempts to build cura-build OSX packages fail due to the 3.6.2 files not existing.

I attempted to bump the version in packaging/setup_osx.py.in and projects/CuraEngine.cmake which may or may not have worked. I have an unrelated issue with the current cura-build head that's causing the built binaries to crash on load.

As a workaround without bumping the versions, I also tried the following:
```
cd "$(brew --repo homebrew/core)"
git pull --noshallow
git checkout -b geos-3.6.2 9208b6018781562676ed237189c8c39d1242f5b9
brew unlink geos
HOMEBREW_NO_AUTO_UPDATE=1 brew install geos
git checkout master
git branch -d geos-3.6.2
git pull
```

Which forced an installation of geos 3.6.2

Again, I'm having what appears to be an unrelated issue with the current HEAD on OSX, so I haven't been able to test if either of these solutions were successful, though both do result in a properly-packaged .app file.

**Comment by Ghostkeeper** [comment]
We stumbled upon this as well when our MacOS server suddenly started updating itself. We've fixed this now so that it builds this from source rather than using the Homebrew version: https://github.com/Ultimaker/cura-build/pull/197
