### ISSUE TITLE
Build on windows fails to init submodules

### ISSUE THREAD

**Issue by lamest** [Ultimaker/cura-build#196]
it can be some environment issue, just asking for help.

building in docker from microsoft/windowsservercore:ltsc2016 with all dependencies installed.
git is installed and i can successfully clone Uranium and exec `git submodule init` without any errors.

Here is the log:

```
[  4%] Performing download step (git clone) for 'Uranium'
Cloning into 'Uranium'...
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2ff09d34 Merge branch '3.5'
CMake Error at C:/cura-build/build/Uranium-prefix/tmp/Uranium-gitclone.cmake:84 (message):
  Failed to init submodules in:
  'C:/cura-build/build/Uranium-prefix/src/Uranium'


mingw32-make[2]: *** [CMakeFiles\Uranium.dir\build.make:89: Uranium-prefix/src/Uranium-stamp/Uranium-download] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:222: CMakeFiles/Uranium.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2
```

here is the failed command:

```
execute_process(
  COMMAND "C:/Program Files/Git/cmd/git.exe" ${git_options} submodule init
  WORKING_DIRECTORY "C:/cura-build/build/CuraEngine-prefix/src/CuraEngine"
  RESULT_VARIABLE error_code
  )
if(error_code)
  message(FATAL_ERROR "Failed to init submodules in: 'C:/cura-build/build/CuraEngine-prefix/src/CuraEngine'")
endif()
```

**Comment by thopiekar** [comment]
Hardcoded execution of git! 😮

**Comment by LipuFei** [comment]
Hi @lamest There is no `git submodule` in Uranium, Cura, and CuraEngine, so you don't need to run `submodule init` at all.

**Comment by lamest** [comment]
> 
> 
> Hardcoded execution path of git! 😮

no its not. its generated by cmake



> 
> 
> Hi @lamest There is no `git submodule` in Uranium, Cura, and CuraEngine, so you don't need to run `submodule init` at all.

tell me about it. cmake wants to init submodules and i dont know any way to change it.

**Comment by LipuFei** [comment]
@lamest This seems to be a problem if you use docker image `mcr.microsoft.com/windows/servercore` with a version earlier than `1809`. You can have a look at this PR https://github.com/Ultimaker/cura-build-environment/pull/71, It uses `servercore:1809` and doesn't have this problem.

**Comment by LipuFei** [comment]
I'll close this issue because you can use `mcr.microsoft.com/windows/servercore:1809` to work around it.
