### ISSUE TITLE
[sos] Link problem with cura-build project

### ISSUE THREAD

**Issue by nateInChina** [Ultimaker/cura-build#204]
ok, I have build cura for few days and have meet so many problems and now i am get closed to success.I have success build cura-environment project and I am sure I have done follows as @Ghostkeeper say:
 1. Build CPython using MSVC 
 2. Compile Protobuf using MSVC.
 3. Compile libArcus using MSVC. Link the MSVC-built Protobuf to it. Install libArcus in your Python installation.
 4. Compile Protobuf again using MinGW.
 5. Compile libArcus again using MinGW. Link the MinGW-built Protobuf to it.
 but I am stop at the step 6:
6. Compile CuraEngine using MinGW. Link the MinGW-built libArcus to it.
step 6 is cura-build project'work, My error was occured when system building CuraEngine in this project. my problem is the same  as #165.  I take Ghostkeeper's suggestion and check the linklibs.rsp, the message is:
![image](https://user-images.githubusercontent.com/11704675/49855360-f73dc400-fe27-11e8-8334-82b93f1ee203.png)
![Uploading image.png…]()
now what should I modify at the begining to change link path in linklibs.rsp?  I have no idea, I am a beginer with Cmake project.  

the error message is too long , I have cut some as follows:
---------------------------------------------------------------------
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x134): undefined reference to `Arcus::Socket::Socket()'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x16d): undefined reference to `Arcus::Socket::addListener(Arcus::SocketListener*)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0xa7a): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x148a): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x1cf5): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x21bb): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.text+0x265b): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
lib_CuraEngine.a(ArcusCommunication.cpp.obj):ArcusCommunication.cpp:(.rdata$.refptr._ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E[.refptr._ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E]+0x0): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
lib_CuraEngine.a(Listener.cpp.obj):Listener.cpp:(.text+0x32): undefined reference to `Arcus::Error::getErrorCode() const'
lib_CuraEngine.a(Listener.cpp.obj):Listener.cpp:(.text+0x42): undefined reference to `Arcus::Error::getErrorMessage[abi:cxx11]() const'
lib_CuraEngine.a(Listener.cpp.obj):Listener.cpp:(.text+0x73): undefined reference to `Arcus::Error::getErrorMessage[abi:cxx11]() const'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x26): undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x4d): undefined reference to `google::protobuf::internal::DestroyMessage(void const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x86): undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xad): undefined reference to `google::protobuf::internal::DestroyMessage(void const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x100): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x140): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x180): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1c0): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x200): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x240): more undefined references to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)' follow
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x638): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x668): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x6d8): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x748): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x76e): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x798): more undefined references to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)' follow
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x915): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x93a): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x9f5): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xb19): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xb99): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xc05): more undefined references to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)' follow
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xee6): undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xf0d): undefined reference to `google::protobuf::internal::DestroyMessage(void const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xf71): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xfa9): undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt32(int, int, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0xffb): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1069): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1081): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1092): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x10eb): undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt32(int, int, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1102): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1113): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1189): undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x11d5): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x11e6): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x11f9): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x120b): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x121d): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1239): undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long long, google::protobuf::io::CodedOutputStream*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x131b): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1418): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1428): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1438): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1448): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1459): more undefined references to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)' follow
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x15f4): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1604): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x17f4): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1804): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1859): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x199d): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x19ae): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x19bf): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x19d3): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x19e7): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1b55): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1c85): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
lib_CuraEngine.a(Cura.pb.cc.obj):Cura.pb.cc:(.text+0x1d45): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
。。。。bala bala
。。。。
。。。。
CMakeFiles\CuraEngine.dir\build.make:99: recipe for target 'CuraEngine.exe' failed
mingw32-make[5]: *** [CuraEngine.exe] Error 1
CMakeFiles\Makefile2:187: recipe for target 'CMakeFiles/CuraEngine.dir/all' failed
mingw32-make[4]: *** [CMakeFiles/CuraEngine.dir/all] Error 2
Makefile:153: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2
CMakeFiles\CuraEngine.dir\build.make:109: recipe for target 'CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build' failed
mingw32-make[2]: *** [CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build] Error 2
CMakeFiles\Makefile2:258: recipe for target 'CMakeFiles/CuraEngine.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/CuraEngine.dir/all] Error 2
Makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
---------------------------------------------------------------------

Apprication to any help!!!!

**Comment by nateInChina** [comment]
linklibs.rsp’s path is : %cura-build project source%\build\CuraEngine-prefix\src\CuraEngine-build\CMakeFiles\CuraEngine.dir

**Comment by LipuFei** [comment]
Hi @nateInChina I've commented in https://github.com/Ultimaker/cura-build/issues/165 (see See https://github.com/Ultimaker/cura-build/issues/165#issuecomment-504918751). It may be helpful to you.

**Comment by LipuFei** [comment]
Hi @nateInChina , from your screenshot, it seems to be using MSVC compiled protobuf library with MinGW. This will not work. MinGW needs to use the protobuf library compiled with MinGW, the static version of which should end with the ".a" file extension. You can check comments in issue #165 

I'll close this issue as a duplicate.
