### ISSUE TITLE
Build on Ubuntu 18.04 fails in cmake

### ISSUE THREAD

**Issue by sk8nfool** [Ultimaker/cura-build#208]
I am trying to build Cura for Ubuntu 18.04. I did the following per the README.md file

$ **git clone http://github.com/Ultimaker/cura-build.git**
Cloning into 'cura-build'...
warning: redirecting to https://github.com/Ultimaker/cura-build.git/
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 2182 (delta 19), reused 31 (delta 19), pack-reused 2146
Receiving objects: 100% (2182/2182), 691.17 KiB | 15.03 MiB/s, done.
Resolving deltas: 100% (1399/1399), done.
$ **cd cura-build/**
$ **mkdir build**
$ **cd build**
$ **cmake ..**
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE

CMake Error at projects/CuraEngine.cmake:1 (find_package):
  By not providing "FindArcus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arcus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Arcus" (requested
  version 1.1) with any of the following names:

    ArcusConfig.cmake
    arcus-config.cmake

  Add the installation prefix of "Arcus" to CMAKE_PREFIX_PATH or set
  "Arcus_DIR" to a directory containing one of the above files.  If "Arcus"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)

-- Configuring incomplete, errors occurred!
See also "/home/braun/Dropbox/Downloads/Cura/x/cura-build/build/CMakeFiles/CMakeOutput.log".
$

I suspect this is because there are dependencies missing BUT the README.md file seem to be missing the list. It just says
```
To build, make sure these dependencies are installed, then clone this repository and run the following commands from your clone:

```
followed by the commands to run - no list!

**Comment by LipuFei** [comment]
Hi @sk8nfool , indeed you need to specify `CMAKE_PREFIX_PATH` to where you installed your build environment. For example:

```
git clone cura-build-environment
...
cmake -DCMAKE_INSTALL_PREFIX=/opt/cura-build-env -DCMAKE_PREFIX_PATH=/opt/cura-build-env


git clone cura-build
...
cmake -DCMAKE_PREFIX_PATH=/opt/cura-build-env
```

**Comment by LipuFei** [comment]
Note that you can now use docker to build Cura AppImage for linux. Check the docker sections in https://github.com/Ultimaker/cura-build-environment and this repository for more details.

**Comment by Ghostkeeper** [comment]
I've added some dependencies for Ubuntu here now: https://github.com/Ultimaker/cura-build#ubuntulinux

Hopefully they are complete. It's hard to tell from an existing development environment.

**Comment by LipuFei** [comment]
Closing this one due to inactivity.
