### ISSUE TITLE
Error on building Cura on Windows 7

### ISSUE THREAD

**Issue by shawnlintw** [Ultimaker/cura-build#21]
I run script on windows7 with mingw32-make 
Cmake with default configures (Not any modify).
And I got this error message as script build protobuf :

[  0%] Built target Python
[  1%] Performing update step for 'Protobuf'
Current branch 15.10 is up to date.
[  2%] Performing configure step for 'Protobuf'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/B00122/Desktop/cmake/bin/Protobuf-prefix/src/Protobuf-build
[  3%] Performing build step for 'Protobuf'
[ 47%] Built target libprotoc
[ 82%] Built target protobuf
[ 97%] Built target protobuf-lite
[ 99%] Built target protoc
[100%] Generating python/lib/google
running build
running build_py
Generating google/protobuf/unittest_pb2.py...
[100%] Built target python_protobuf
[  4%] Performing install step for 'Protobuf'
[ 47%] Built target libprotoc
[ 82%] Built target protobuf
[ 97%] Built target protobuf-lite
[ 99%] Built target protoc
[100%] Generating python/lib/google
running build
running build_py
Generating google/protobuf/unittest_pb2.py...
[100%] Built target python_protobuf
Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/Users/B00122/Desktop/cmake/bin/inst/bin/protoc.exe
-- Up-to-date: C:/Users/B00122/Desktop/cmake/bin/inst/lib/liblibprotoc.a
-- Up-to-date: C:/Users/B00122/Desktop/cmake/bin/inst/lib/libprotobuf.a
-- Up-to-date: C:/Users/B00122/Desktop/cmake/bin/inst/lib/libprotobuf-lite.a
Makefile:93: recipe for target 'install' failed
CMakeFiles\Protobuf.dir\build.make:72: recipe for target 'Protobuf-prefix/src/Protobuf-stamp/Protobuf-install' failed
CMakeFiles\Makefile2:253: recipe for target 'CMakeFiles/Protobuf.dir/all' failed
Makefile:148: recipe for target 'all' failed

C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option:
 'google_test_dir'
  warnings.warn(msg)
protoc is not installed nor found in ../src.  Please compile it or install the b
inary package.
C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option:
 'google_test_dir'
  warnings.warn(msg)
protoc is not installed nor found in ../src.  Please compile it or install the b
inary package.
CMake Error at cmake_install.cmake:53 (file):
  file INSTALL cannot find
  "C:/Users/B00122/Desktop/cmake/bin/Protobuf-prefix/src/Protobuf-build/python/l
ib/google".

mingw32-make[3]: *** [install] Error 1
mingw32-make[2]: *** [Protobuf-prefix/src/Protobuf-stamp/Protobuf-install] Error
 2
mingw32-make[1]: *** [CMakeFiles/Protobuf.dir/all] Error 2
mingw32-make: *** [all] Error 2

**Comment by awhiemstra** [comment]
Please make sure to run the env_win32.bat script from your build directory. This makes sure to set the path to the built Protoc, so the python bits can be built properly.

**Comment by shawnlintw** [comment]
Hello,  
Thanks.  I run env_win32.bat before I run make and it solve the Protobuf build problem.
However, I got another error message when script excuse the "SIP" segment.
Here is the message :
.
.
.
.
siplib.o:siplib.c:(.text+0xae8d): undefined reference to `_imp__PyUnicode_FromString'
siplib.o:siplib.c:(.text+0xaf2d): undefined reference to `_imp__PyCFunction_NewEx'
siplib.o:siplib.c:(.text+0xaf44): undefined reference to `_imp__PyImport_ImportModule'
siplib.o:siplib.c:(.text+0xaf5f): undefined reference to `_imp__PyObject_GetAttrString'
siplib.o:siplib.c:(.text+0xaf7a): undefined reference to `_imp__PyObject_CallFunctionObjArgs'
siplib.o:siplib.c:(.text+0xb076): undefined reference to `_imp__Py_AtExit'
siplib.o:siplib.c:(.text+0xb092): undefined reference to `_imp__PyThreadState_Get'
C:/Program Files (x86)/mingw-w64/i686-4.9.0-posix-dwarf-rt_v3-rev2/mingw32/bin/.
./lib/gcc/i686-w64-mingw32/4.9.0/../../../../i686-w64-mingw32/bin/ld.exe: siplib.o: bad reloc address 0x0 in section `.data'
collect2.exe: error: ld returned 1 exit status
Makefile:36: recipe for target 'sip.pyd' failed
mingw32-make[4]: *** [sip.pyd] Error 1
Makefile:3: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2
CMakeFiles\Sip.dir\build.make:112: recipe for target 'Sip-prefix/src/Sip-stamp/S
ip-build' failed
mingw32-make[2]: *** [Sip-prefix/src/Sip-stamp/Sip-build] Error 2
CMakeFiles\Makefile2:435: recipe for target 'CMakeFiles/Sip.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/Sip.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2


Does that means I must install or excuse something before I build Cura ?

My system already install python 3.4, perl and excuse the 32-bit builds.

**Comment by shawnlintw** [comment]
Hello, 
I know the failed reason , that is I am using mingw32-make, 32 bits compiler and using the python 3.4 64 bits and PyQt 5.4 64 bits.   
When I reinstall the 32 bits library and everything is fine.

Please close this issue thanks

**Comment by Ghostkeeper** [comment]
Thanks for sharing your solution. I'm sure many will benefit from it when they google your issue :smiley:
