### ISSUE TITLE
have built cura but won't start

### ISSUE THREAD

**Issue by Younghyo** [Ultimaker/cura-build#211]
I have built cura on windows. When I start Cura.exe, it closes immediately without any error message, and 
even cura.log file isn't created. I don't know what CuraCLI.exe is, but it seems okay to start but it crashes as I click some button such as 'PREVIEW' button. For CuraCLI.exe, cura.log file has been made.
[cura.log](https://github.com/Ultimaker/cura-build/files/2924460/cura.log)

I thought I did something wrong so I changed my environment to Linux. In there, the same thing happens. AppImage has been made, but it also closes immediately after start.

So I switched the Cura repository to older version such as '4.0' and '3.6'. It was not helpful also.
How can I find more clues in this case?

**Comment by Ghostkeeper** [comment]
This looks like a duplicate of https://github.com/Ultimaker/Cura/issues/5392. You can find more information there. In particular, you need to make sure that you use the same version of Qt as we do: 5.10.1. We've found some backwards compatibility issues in 5.11.

**Comment by Younghyo** [comment]
I solved the problem referencing this issue[https://github.com/Ultimaker/cura-build/issues/47].

In Linux environment with docker.
When I start using AppImage there is no any message or log to see with immediate close.
But I can see if i start by 'python3 cura_app.py'.
It was a problem couldn't find 'UM' module.
It is because 'UM' module is built in 'build/inst/lib' path, not the '/usr/local/lib'.
So I add the path to $PYTHONPATH. Finally it starts well.

In Windows.
I don't know till now. I guess this is also similar to the Linux thing..
