### ISSUE TITLE
Cura build exe in Windows

### ISSUE THREAD

**Issue by DapDeveloper** [Ultimaker/cura-build#212]
I installed all dependencies and i'm able to run cura_app.py from CMD. Now i want to create the installer to install this version of cura on other PC. I read that i need to compile this repo that create an executable. I tried to compile using Msys2 64bit and the MinGW and make with mingw32-make but i have some issue when configure step Uranium :

Utente@DESKTOP-9UBIAOK MINGW64 /c/buildCura/cura-build-master/cura-build-master/build
# mingw32-make
[  2%] Performing update step for 'Uranium'
HEAD is up to date.
[  4%] Performing configure step for 'Uranium'
--
-- Using CURA_BINARY_DATA_DIRECTORY from set of environment variables...
-- Found PythonInterp: C:/msys64/mingw64/bin/python3.exe (found suitable version "3.7.2", minimum required is "3.5.0")
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.15") found components:  doxygen missing components:  dot
-- Found Gettext: C:/msys64/mingw64/bin/msgmerge.exe (found version "0.19.8.1")
CMake Warning at cmake/UraniumTranslationTools.cmake:88 (message):
  GETTEXT_MSGINIT_EXECUTABLE is undefined!

  Skipping to create i18n-create-po* targets...
Call Stack (most recent call first):
  CMakeLists.txt:46 (CREATE_TRANSLATION_TARGETS)

CMake Warning at cmake/UraniumTranslationTools.cmake:99 (message):
  CURA_BINARY_DATA_DIRECTORY is not set!
Call Stack (most recent call first):
  CMakeLists.txt:46 (CREATE_TRANSLATION_TARGETS)

-- Creating target i18n-update-po
-- Creating target i18n-create-mo
-- Creating target i18n-update-po-de_DE
-- Creating target i18n-create-mo-de_DE
-- Creating target i18n-update-po-es_ES
-- Creating target i18n-create-mo-es_ES
-- Creating target i18n-update-po-fi_FI
-- Creating target i18n-create-mo-fi_FI
-- Creating target i18n-update-po-fr_FR
-- Creating target i18n-create-mo-fr_FR
-- Creating target i18n-update-po-hu_HU
-- Creating target i18n-create-mo-hu_HU
-- Creating target i18n-update-po-it_IT
-- Creating target i18n-create-mo-it_IT
-- Creating target i18n-update-po-ja_JP
-- Creating target i18n-create-mo-ja_JP
-- Creating target i18n-update-po-ko_KR
-- Creating target i18n-create-mo-ko_KR
-- Creating target i18n-update-po-nl_NL
-- Creating target i18n-create-mo-nl_NL
-- Creating target i18n-update-po-pl_PL
-- Creating target i18n-create-mo-pl_PL
-- Creating target i18n-update-po-pt_BR
-- Creating target i18n-create-mo-pt_BR
-- Creating target i18n-update-po-pt_PT
-- Creating target i18n-create-mo-pt_PT
-- Creating target i18n-update-po-ru_RU
-- Creating target i18n-create-mo-ru_RU
-- Creating target i18n-update-po-tr_TR
-- Creating target i18n-create-mo-tr_TR
-- Creating target i18n-update-po-zh_CN
-- Creating target i18n-create-mo-zh_CN
-- Creating target i18n-update-po-zh_TW
-- Creating target i18n-create-mo-zh_TW
-- Configuring done
-- Generating done
-- Build files have been written to: C:/buildCura/cura-build-master/cura-build-master/build/Uranium-prefix/src/Uranium-build
[  6%] Performing build step for 'Uranium'
Scanning dependencies of target i18n-create-mo-nl_NL
Sintassi del comando errata.
mingw32-make[5]: *** [CMakeFiles\i18n-create-mo-nl_NL.dir\build.make:56: i18n-create-mo-nl_NL] Error 1
mingw32-make[4]: *** [CMakeFiles\Makefile2:744: CMakeFiles/i18n-create-mo-nl_NL.dir/all] Error 2
mingw32-make[3]: *** [Makefile:150: all] Error 2
mingw32-make[2]: *** [CMakeFiles\Uranium.dir\build.make:110: Uranium-prefix/src/Uranium-stamp/Uranium-build] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:184: CMakeFiles/Uranium.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

Someone who have done the executable can give me support to fix this problem?
Thanks

**Comment by Ghostkeeper** [comment]
I think the easiest solution would be to install Gettext. CMake should then just find it on your system.

**Comment by DapDeveloper** [comment]
> I think the easiest solution would be to install Gettext. CMake should then just find it on your system.
Thanks,
I tried to copy the compiled Uranium source to cura_build-master/build/Uranium and deleted the Uranium cmake from /projects . Now i fixed this error but i have new error: 

[ 84%] Completed 'cura-binary-data'
[ 96%] Built target cura-binary-data
[ 96%] Built target projects
running cx_Freeze
running build_exe
Traceback (most recent call last):
  File "setup.py", line 191, in <module>
    executables = executables
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\pythoninstall\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\pythoninstall\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\pythoninstall\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\freezer.py", line 616, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\freezer.py", line 342, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 659, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 351, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'cura'
mingw32-make[2]: *** [CMakeFiles\build_bundle.dir\build.make:57: build_bundle] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:259: CMakeFiles/build_bundle.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

**Comment by Ghostkeeper** [comment]
Hmm, looks like it didn't put the `cura` repository on your PYTHONPATH correctly while packaging?

**Comment by DapDeveloper** [comment]
Thanks, i didn't put the cura repository. Now i put it and i tried to recompile but give me another error.
[ 84%] Completed 'cura-binary-data'
[ 96%] Built target cura-binary-data
[ 96%] Built target projects
running cx_Freeze
running build_exe
Traceback (most recent call last):
  File "setup.py", line 191, in <module>
    executables = executables
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\pythoninstall\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\pythoninstall\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\pythoninstall\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\freezer.py", line 616, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\freezer.py", line 342, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 661, in IncludePackage
    self._ImportAllSubModules(module, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 288, in _ImportAllSubModules
    recursive)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 280, in _ImportAllSubModules
    deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 404, in _InternalImportModule
    parentModule, namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 475, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 589, in _ScanCode
    topLevel = False)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 570, in _ScanCode
    fromList, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 211, in _EnsureFromList
    self._ImportModule(subModuleName, deferredImports, caller)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 311, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 404, in _InternalImportModule
    parentModule, namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 475, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 570, in _ScanCode
    fromList, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 211, in _EnsureFromList
    self._ImportModule(subModuleName, deferredImports, caller)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 311, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 404, in _InternalImportModule
    parentModule, namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 417, in _LoadModule
    namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 486, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 475, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 589, in _ScanCode
    topLevel = False)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 565, in _ScanCode
    module, relativeImportIndex)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 311, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 404, in _InternalImportModule
    parentModule, namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 417, in _LoadModule
    namespace)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 486, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 464, in _LoadModule
    self._RunHook("load", module.name, module)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\finder.py", line 537, in _RunHook
    method(self, *args)
  File "C:\pythoninstall\lib\site-packages\cx_Freeze\hooks.py", line 615, in load_tkinter
    tclSourceDir = os.environ["TCL_LIBRARY"]
  File "C:\pythoninstall\lib\os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'TCL_LIBRARY'
mingw32-make[2]: *** [CMakeFiles\build_bundle.dir\build.make:57: build_bundle] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:259: CMakeFiles/build_bundle.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

Have you any idea?

**Comment by Ghostkeeper** [comment]
No, no idea actually. A quick Google search gives me this result that might fix it for you though: https://stackoverflow.com/questions/35533803/keyerror-tcl-library-when-i-use-cx-freeze

**Comment by DapDeveloper** [comment]
I fixed the problem running in CMD : 
set TCL_LIBRARY=C:\Program Files\Python35-32\tcl\tcl8.6
set TK_LIBRARY=C:\Program Files\Python35-32\tcl\tk8.6
Thanks a lot for the support. Now i have buit the excutable of cura , but when i install it and try to run the cura application , give me this error: 
cx_Freeze:Python error in main script
Exception: No module named 'PyQt5.sip'
Original Exception :No module named 'PyQt5.sip'
I tried in python to import PyQt5.sip and works...

**Comment by Ghostkeeper** [comment]
Maybe you could try installing a 64-bit version of CPython?

It needs TCL to build the installer. Maybe you're using a 32-bit version of TCL which is linked to 32-bit versions of your system DLLs, but since you're using a 64-bit operating system those don't exist? Just guessing in the dark here though.

**Comment by DapDeveloper** [comment]
Thanks,
I have installed python 64 bit. What do you mean for CPython 64bit? I search on google CPython but i found Cython , is the same? Thanks  a lot for support

**Comment by DapDeveloper** [comment]
I tried to change the tcl directory from an old python (3.5.2) and now this problem is fixed but i have another problem. Cura don't find PyQt5.sip ...
![error2](https://user-images.githubusercontent.com/30629822/55322016-642ea580-547b-11e9-9b22-802d1ffc4b11.PNG)

**Comment by Ghostkeeper** [comment]
Cython is not the same as CPython. CPython is the default implementation of the Python language distributed by python.org. Cython is an alternative implementation of a superset of the Python language that allows you to put C code in between your Python code.

Did you get PyQt5.sip installed in your Python environment?

**Comment by DapDeveloper** [comment]
Thanks, now i understand.
I have a Python environment installed in C:\pythoninstall.
The version is 3.5.2 and has sip installed(i tried cura_app.py and works). I make the package with MSYS2 and this have another version of python without sip. I need to install the same version of python in MSYS2. I need to make the package with CMD or MSYS2 ? Sorry but i'm a bit confused

**Comment by Ghostkeeper** [comment]
I would use normal command line with MinGW-w64 rather than MSYS, but either should work. In the end they are all just Windows binaries anyway. Don't mix-and-match.

**Comment by DapDeveloper** [comment]
I have installed MinGW-w64 , and i made the executable , but i have the same problem , Cura don't find PyQt5.sip. Now i'm using the CMD, i tried "import PyQt5.sip" in python and works.
![error2](https://user-images.githubusercontent.com/30629822/55340615-568e1580-54a5-11e9-82f2-3392871b0eef.PNG)

**Comment by Ghostkeeper** [comment]
Maybe you should then try adding a `print(sys.path)` to that cura_app.py and look through those paths to see if `PyQt5.sip` is actually on there.

**Comment by DapDeveloper** [comment]
Maybe i found the problem. When i run the mingw32-make without running env_win64.bat first , works fine(but i have the problem no Module named Pyqt5.sip). If i run env_win64.bat first, the mingw32-make generate the error "ImportError: No module named 'cura'", but i have the cura repo in PYTHONPATH. 
I think that there is a problem with paths. Have you any idea because it generate me this error after i run the env_win64.bat? Thanks

**Comment by DapDeveloper** [comment]
I want to try to install  CPython 64bit maybe i fix the problems .
 How can i do this on Windows 10 ? Thanks

**Comment by DapDeveloper** [comment]
I tried to restart the PC and now the problem PyQt5.sip is fixed(The paths was not updated).
Now i have the same problems with DLL. I will try with other version of CPython, maybe i fix this problem.

**Comment by Ghostkeeper** [comment]
Restarting the terminal should be sufficient to update environment variables.

**Comment by DapDeveloper** [comment]
I tried the python versions from 3.5.0 to 3.7.3 . I tried also change the cx_Freeze versions but I have the same problem...
![error](https://user-images.githubusercontent.com/30629822/55416530-3cb90500-556f-11e9-8d11-beb0eadc8f59.PNG).
What can i do to fix this problem?
Thanks,

**Comment by Ghostkeeper** [comment]
Cura's official builds are currently using CPython 3.5.2.

This error message is different though. Which DLL is it not finding now?

**Comment by DapDeveloper** [comment]
![dll1](https://user-images.githubusercontent.com/30629822/55459891-e68ca600-55f0-11e9-83ce-81a6d08f8466.PNG)
![dll2](https://user-images.githubusercontent.com/30629822/55459893-e8566980-55f0-11e9-9b3f-448527d88b9b.PNG)
![dll3](https://user-images.githubusercontent.com/30629822/55459897-e9879680-55f0-11e9-973d-de20e627b44a.PNG)
![dll4](https://user-images.githubusercontent.com/30629822/55459932-fc9a6680-55f0-11e9-8e16-36ee95c60c51.PNG)
![dll5](https://user-images.githubusercontent.com/30629822/55459936-002ded80-55f1-11e9-8570-91670a90eeae.PNG)

I have done some screenshot with DLL that's not finding.

**Comment by Ghostkeeper** [comment]
You should have a serious look at your system's PATH if it's not finding the core Windows DLLs, I think.

**Comment by DapDeveloper** [comment]
I found this on stackoverflow
![stack](https://user-images.githubusercontent.com/30629822/55467077-cb299700-5600-11e9-9532-31d9ecc13e40.png). So the core Windows DLLs are found but Dependency Walker don't see this because is not updated to Windows 10.

**Comment by DapDeveloper** [comment]
I found the problem but i don't know how to fix it. The problem is on cura_app.py:
LINE121: from cura.CuraApplication import CuraApplication
When the program run this command generate the DLL error.
Have you any idea?Thanks

**Comment by Ghostkeeper** [comment]
CuraApplication is not a DLL. However inside the CuraApplication file it will import a couple of things that are DLLs (there are like 120 lines of imports in that file). DLLs imported in that file are numpy and a bunch of PyQt5 DLLs. Also there are other imports, like the plug-ins, that will eventually result in other DLLs being imported like libSavitar and libArcus.

I'd expect your error message to show a sub-error in the form of a stack trace.

**Comment by DapDeveloper** [comment]
I didn't understand a thing well. I have to do the executable of my modified cura version, but when I run the mingw32-make command all the repositories (arcus, uranium, cura, cura-binaries) are downloaded from github so the package that is created is not with the my version but with the version that is on github. How can I generate the executable with my version? Thanks

**Comment by Ghostkeeper** [comment]
You would need to adjust the URLs in the projects folder to link to your own repositories.

**Comment by DapDeveloper** [comment]
Thanks, i understood.
When i compiled CuraEngine locally i used the flags > cmake -G "MinGW Makefiles" .. -DProtobuf_LIBRARIES="C:\Program Files (x86)\protobuf\lib\libprotobuf.a" -DProtobuf_INCLUDE_DIR="C:\Program Files (x86)\protobuf\include" to indicate the protobuf library. <
When i compile CuraEngine with cura-build makefile , this flags are not included and i have the error: Protobuf not found ...
How can i insert this flags on cura-build makefiles? Thanks

**Comment by Ghostkeeper** [comment]
The way I've done it once in a while for debugging is this:

1. Try to build cura-build, which fails because it can't find a dependency of one of the dependencies.
2. Navigate into the prefix directory of the dependency that failed. In your case something like `CuraEngine-prefix/src`.
3. Use CMake there to change the CMake variables you like.
4. Configure and Generate.
5. Run the build on cura-build again.

**Comment by DapDeveloper** [comment]
I found that SIP library are not installed correctly. Now i removed all libraries and i reinstall all.
During the sip library installation, give me an error:
int_convertors.c
Generating Code...
        cl -c -nologo -Zm200 -Zc:wchar_t- -FS -Zc:strictStrings -D_HAS_EXCEPTIONS=0 -O2 -MD -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -DNDEBUG -DUNICODE -DWIN32 -I. -IC:\py3.5.2\include -Fo @C:\Users\Utente\AppData\Local\Temp\nmADED.tmp
bool.cpp
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DLL /MANIFEST /MANIFESTFILE:sip.pyd.manifest /SUBSYSTEM:CONSOLE /INCREMENTAL:NO /OUT:sip.pyd @C:\Users\Utente\AppData\Local\Temp\nmAE1C.tmp
python35.lib(python35.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"' : return code '0x458'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
I have some conflicts with libraries.
I checked the python version(64bit) i don't understand why give me this error.
Any idea?
Thanks

**Comment by Ghostkeeper** [comment]
> python35.lib(python35.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'

This seems like a conflict between 32-bit builds and 64-bit builds to me.

**Comment by DapDeveloper** [comment]
When i build protobuf with mingw32-make and nmake , install protobuf in C:\Program Files and  C:\Program Files (x86) . I don't understand why don't install both in C:\Program Files ? Maybe is this the conflict?

**Comment by DapDeveloper** [comment]
I rebuild all packages and now i fixed the dll error but Cura start, show the logo , and close . 
Cura log:
2019-04-08 11:04:02,021 - INFO - [MainThread] cura.CuraApplication.run [713]: Initializing quality manager
2019-04-08 11:04:02,032 - DEBUG - [MainThread] cura.Machines.QualityManager.initialize [136]: Lookup tables updated.
2019-04-08 11:04:02,033 - INFO - [MainThread] cura.CuraApplication.run [718]: Initializing machine manager
2019-04-08 11:04:02,035 - INFO - [MainThread] cura.CuraApplication.run [721]: Initializing container manager
2019-04-08 11:04:02,036 - INFO - [MainThread] cura.CuraApplication.run [724]: Initializing machine error checker
2019-04-08 11:04:03,470 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [158]: Loading theme file: C:\Program Files\Ultimaker Cura 0.0\resources\themes\cura-light\theme.json
2019-04-08 11:04:03,597 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [230]: Loaded theme C:\Program Files\Ultimaker Cura 0.0\resources\themes\cura-light
2019-04-08 11:04:03,607 - DEBUG - [MainThread] UM3NetworkPrinting.src.DiscoverUM3Action._createAdditionalComponentsView [196]: Creating additional ui components for UM3.
2019-04-08 11:04:03,758 - DEBUG - [MainThread] UM3NetworkPrinting.src.DiscoverUM3Action.startDiscovery [47]: Starting device discovery.
2019-04-08 11:04:03,864 - DEBUG - [MainThread] UM.Controller.setActiveStage [149]: Setting active stage to PrepareStage
2019-04-08 11:04:03,866 - DEBUG - [MainThread] UM.Controller.setActiveView [91]: Setting active view to SolidView
2019-04-08 11:04:03,879 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [107]: Creating model checker view.
Fatal Python error: Aborted

**Comment by Ghostkeeper** [comment]
> When i try to run CuraEngine.exe from install directory, i have the error libArcus.dll not found

Then probably you don't have a MinGW-version of libArcus, or not in the location that CuraEngine is run from.

> I installed PyQt5 with pip (pip3 install PyQt) is right?

It's intended to be installed via the `cura-build-environment` repository: https://github.com/Ultimaker/cura-build-environment

Installing with Pip is what I do to create a development environment. However you need to be sure to get all the required components of Qt 5.10, including QtQuick-Controls.

**Comment by DapDeveloper** [comment]
Thanks,
Now i tried to build the cura-build-environment, but when compile Arcus generate the follow error:

Scanning dependencies of target Arcus
[  5%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.obj
cl : Command line warning D9002 : ignoring unknown option '-m64'
Socket.cpp
g:\newpackages\cura-build-environment\build\arcus-prefix\src\arcus\src\Socket_p.h(41): fatal error C1083: Cannot open include file: 'google/protobuf/message.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

How can i fix it?Thanks

**Comment by DapDeveloper** [comment]
I understood that google/protobuf/message.h is located on %INSTALL_DIR% but when compile Arcus don't find it. I'm thinking to copy %INSTALL_DIR% content in cura-build-environment\build\arcus-prefix\src\arcus\src\. Is a good idea, or maybe i will have problems with linking? Thanks

**Comment by DapDeveloper** [comment]
I fixed this problem by renaming the %INSTALL_DIR% . Now i have another problem.
I build the cura-build-environment but when i try to build Cura-build(cmake -G "MinGW Makefiles" ..  -DPYTHON_EXECUTABLE="C:\py3.5.2\python.exe" -DSIGN_PACKAGE:BOOL=OFF -DCMAKE_PREFIX_PATH="install") generate this:
G:/newPackages/cura-build-environment-4.0.0/build/installation/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/G_/newPackages/cura-build-environment-4.0.0/build/Protobuf-prefix/src/Protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@D_K@Z]+0x10): undefined reference to `__GSHandlerCheck'
G:/newPackages/cura-build-environment-4.0.0/build/installation/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/G_/newPackages/cura-build-environment-4.0.0/build/Protobuf-prefix/src/Protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?do_put@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MEBA?AV?$ostreambuf_iterator@DU?$char_traits@D@std@@@2@V32@AEAVios_base@2@DN@Z]+0x1c): more undefined references to `__GSHandlerCheck' follow
G:/newPackages/cura-build-environment-4.0.0/build/installation/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/G_/newPackages/cura-build-environment-4.0.0/build/Protobuf-prefix/src/Protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?_Init@?$numpunct@D@std@@IEAAXAEBV_Locinfo@2@_N@Z]+0x18): undefined reference to `__CxxFrameHandler3'
G:/newPackages/cura-build-environment-4.0.0/build/installation/lib/libprotobuf.lib(CMakeFiles/libprotobuf.dir/G_/newPackages/cura-build-environment-4.0.0/build/Protobuf-prefix/src/Protobuf/src/google/protobuf/stubs/int128.cc.obj):(.xdata[$unwind$?catch$0@?0??_Init@?$numpunct@D@std@@IEAAXAEBV_Locinfo@2@_N@Z@4HA]+0x8): undefined reference to `__CxxFrameHandler3'
collect2.exe: error: ld returned 1 exit status
mingw32-make[5]: *** [CMakeFiles\CuraEngine.dir\build.make:100: CuraEngine.exe] Error 1
mingw32-make[4]: *** [CMakeFiles\Makefile2:188: CMakeFiles/CuraEngine.dir/all] Error 2
mingw32-make[3]: *** [Makefile:154: all] Error 2
mingw32-make[2]: *** [CMakeFiles\CuraEngine.dir\build.make:111: CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:259: CMakeFiles/CuraEngine.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

**Comment by Ghostkeeper** [comment]
Hard to say. All of these errors are in code that we did not write.

At first glance I'd guess that you're linking Protobuf compiled with MSVC to a CuraEngine compiled with MinGW. 90% of the cases that there's a linker error with undefined references, in my experience, it's a problem of using libraries that were made with a different compiler. It could of course still be something else.

You need to make sure that you have two versions of libArcus and protobuf: One compiled with MinGW and one compiled with MSVC. The version compiled with MinGW needs to link to CuraEngine and the version compiled with MSVC needs to be finalised as a Python library.

**Comment by DapDeveloper** [comment]
OK, but if i run cura-build-environment , why i have this problems? Cura build environment compile protobuf and arcus, so need to be correct. Now i'm trying to recompile all sources...
Thanks a lot for the support.

**Comment by DapDeveloper** [comment]
I fixed this problem. Now i buit the executable. I reinstalled all dependencies and now works.
Thanks for the support
