### ISSUE TITLE
Creating package error NSIS

### ISSUE THREAD

**Issue by JithuPG** [Ultimaker/cura-build#214]
Error get when creating pacakge 

Error Log : 

Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: cura-build
CPack: - Install project: cura-build
CPack: -   Install component: _cura
CPack: -   Install component: arduino
CPack: -   Install component: vcredist
CPack: Create package
CPack Error: Problem running NSIS command: "C:/Program Files (x86)/NSIS/makensis.exe" "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi"
Please check F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: p
mingw32-make: *** [Makefile:72: package] Error 1

What would be it ...?

**Comment by JithuPG** [comment]
While inspection the error log of NSIS found 
NSIS Error Log : 

Error in script "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi" on line 542 -- aborting creation process

Futher Look into project.nsi

![error](https://user-images.githubusercontent.com/10563956/55422822-2c6a4f80-559a-11e9-83e1-69d56afc5d92.png)

while searching web I found Link : 

https://nsis.sourceforge.io/File_Association

but can't figure it out what to do?

**Comment by Ghostkeeper** [comment]
> Error in script "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi" on line 542 -- aborting creation process

I'd expect there to be a bit more to know from the log entries before this error. Is there any more?

**Comment by JithuPG** [comment]
YP

Error Log : 


# Run command: "C:/Program Files (x86)/NSIS/makensis.exe" "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi"
# Output:
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh

Processing script file: "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi" (ACP)

!insertmacro: select_NT_profile

Function: "select_NT_profile"

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=0, nonequal=environment_single

DetailPrint: "Selected environment for all users"

Push: all

Return

DetailPrint: "Selected environment for current user only."

Push: current

Return

FunctionEnd

!insertmacro: end of select_NT_profile

!insertmacro: select_NT_profile

Function: "un.select_NT_profile"

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=0, nonequal=environment_single

DetailPrint: "Selected environment for all users"

Push: all

Return

DetailPrint: "Selected environment for current user only."

Push: current

Return

FunctionEnd

!insertmacro: end of select_NT_profile

!define: "NT_current_env"="HKCU "Environment""

!define: "NT_all_env"="HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment""

!define: "WriteEnvStr_RegKey"="HKCU "Environment""

Function: "AddToPath"

Exch($0,0)

Push: $1

Push: $2

Push: $3

IfFileExists: "$0\*.*" ?  : AddToPath_done

ReadEnvStr: PATH->$1

StrLen $2 "$1"

IntCmp $2:0 equal=CheckPathLength_ShowPathWarning, < CheckPathLength_Done, > CheckPathLength_Done

MessageBox: 48: "Warning! PATH too long installer unable to modify PATH!"

Goto: AddToPath_done

Push: $1;

Push: $0;

Call "StrStr"

Pop: $2

StrCmp "$2" "" equal=, nonequal=AddToPath_done

Push: $1;

Push: $0\;

Call "StrStr"

Pop: $2

StrCmp "$2" "" equal=, nonequal=AddToPath_done

GetFullPathName: $0->$3 (4583984)

Push: $1;

Push: $3;

Call "StrStr"

Pop: $2

StrCmp "$2" "" equal=, nonequal=AddToPath_done

Push: $1;

Push: $3\;

Call "StrStr"

Pop: $2

StrCmp "$2" "" equal=, nonequal=AddToPath_done

Call "IsNT"

Pop: $1

StrCmp "$1" "1" equal=AddToPath_NT, nonequal=

StrCpy $1 "$WINDIR" (2) ()

FileOpen: $1\autoexec.bat as a -> $1

FileSeek: fp=$1, ofs=-1, mode=END, output=

FileReadByte: $1->$2

IntCmp $2:26 equal=0, < +2, > +2

FileSeek: fp=$1, ofs=-1, mode=END, output=

FileWrite: 

SET PATH=%PATH%;$3

->$1

FileClose: $1

Goto: AddToPath_done

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=ReadAllKey, nonequal=

ReadRegStr $1 HKCU\Environment\PATH

Goto: DoTrim

ReadRegStr $1 HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PATH

StrCmp "$1" "" equal=AddToPath_NTdoIt, nonequal=

Push: $1

Call "Trim"

Pop: $1

StrCpy $0 "$1;$0" () ()

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=WriteAllKey, nonequal=

WriteRegExpandStr: HKCU\Environment\PATH=$0

Goto: DoSend

WriteRegExpandStr: HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PATH=$0

SendMessage: (timeout=5000)(0xFFFF,0x001A,0,STR:Environment)

Pop: $3

Pop: $2

Pop: $1

Pop: $0

FunctionEnd

Function: "un.RemoveFromPath"

Exch($0,0)

Push: $1

Push: $2

Push: $3

Push: $4

Push: $5

Push: $6

IntFmt: 26->$6 (fmt:%c)

Call "un.IsNT"

Pop: $1

StrCmp "$1" "1" equal=unRemoveFromPath_NT, nonequal=

StrCpy $1 "$WINDIR" (2) ()

FileOpen: $1\autoexec.bat as r -> $1

GetTempFileName -> $4

FileOpen: $4 as w -> $2

GetFullPathName: $0->$0 (4583984)

StrCpy $0 "SET PATH=%PATH%;$0" () ()

Goto: unRemoveFromPath_dosLoop

FileRead: $1->$3 (max:)

StrCpy $5 "$3" (1) (-1)

StrCmp "$5" "$6" equal=0, nonequal=+2

StrCpy $3 "$3" (-1) ()

StrCmp "$3" "$0

" equal=unRemoveFromPath_dosLoopRemoveLine, nonequal=

StrCmp "$3" "$0

" equal=unRemoveFromPath_dosLoopRemoveLine, nonequal=

StrCmp "$3" "$0" equal=unRemoveFromPath_dosLoopRemoveLine, nonequal=

StrCmp "$3" "" equal=unRemoveFromPath_dosLoopEnd, nonequal=

FileWrite: $3->$2

Goto: unRemoveFromPath_dosLoop

Goto: unRemoveFromPath_dosLoop

FileClose: $2

FileClose: $1

StrCpy $1 "$WINDIR" (2) ()

Delete: "$1\autoexec.bat"

CopyFiles: (silent) "$4" -> "$1\autoexec.bat", size=0KB

Delete: "$4"

Goto: unRemoveFromPath_done

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=unReadAllKey, nonequal=

ReadRegStr $1 HKCU\Environment\PATH

Goto: unDoTrim

ReadRegStr $1 HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PATH

StrCpy $5 "$1" (1) (-1)

StrCmp "$5" ";" equal=+2, nonequal=

StrCpy $1 "$1;" () ()

Push: $1

Push: $0;

Call "un.StrStr"

Pop: $2

StrCmp "$2" "" equal=unRemoveFromPath_done, nonequal=

StrLen $3 "$0;"

StrLen $4 "$2"

StrCpy $5 "$1" (-$4) ()

StrCpy $6 "$2" () ($3)

StrCpy $3 "$5$6" () ()

StrCpy $5 "$3" (1) (-1)

StrCmp "$5" ";" equal=0, nonequal=+2

StrCpy $3 "$3" (-1) ()

StrCmp "$ADD_TO_PATH_ALL_USERS" "1" equal=unWriteAllKey, nonequal=

WriteRegExpandStr: HKCU\Environment\PATH=$3

Goto: unDoSend

WriteRegExpandStr: HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PATH=$3

SendMessage: (timeout=5000)(0xFFFF,0x001A,0,STR:Environment)

Pop: $6

Pop: $5

Pop: $4

Pop: $3

Pop: $2

Pop: $1

Pop: $0

FunctionEnd

!insertmacro: IsNT

Function: "IsNT"

Push: $0

ReadRegStr $0 HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentVersion

StrCmp "$0" "" equal=0, nonequal=IsNT_yes

Pop: $0

Push: 0

Return

Pop: $0

Push: 1

FunctionEnd

!insertmacro: end of IsNT

!insertmacro: IsNT

Function: "un.IsNT"

Push: $0

ReadRegStr $0 HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentVersion

StrCmp "$0" "" equal=0, nonequal=IsNT_yes

Pop: $0

Push: 0

Return

Pop: $0

Push: 1

FunctionEnd

!insertmacro: end of IsNT

!insertmacro: StrStr

Function: "StrStr"

Exch($R1,0)

Exch(st(1),0)

Exch($R2,0)

Push: $R3

Push: $R4

Push: $R5

StrLen $R3 "$R1"

StrCpy $R4 "0" () ()

StrCpy $R5 "$R2" ($R3) ($R4)

StrCmp "$R5" "$R1" equal=done, nonequal=

StrCmp "$R5" "" equal=done, nonequal=

IntOp: $R4=$R4+1

Goto: loop

StrCpy $R1 "$R2" () ($R4)

Pop: $R5

Pop: $R4

Pop: $R3

Pop: $R2

Exch($R1,0)

FunctionEnd

!insertmacro: end of StrStr

!insertmacro: StrStr

Function: "un.StrStr"

Exch($R1,0)

Exch(st(1),0)

Exch($R2,0)

Push: $R3

Push: $R4

Push: $R5

StrLen $R3 "$R1"

StrCpy $R4 "0" () ()

StrCpy $R5 "$R2" ($R3) ($R4)

StrCmp "$R5" "$R1" equal=done, nonequal=

StrCmp "$R5" "" equal=done, nonequal=

IntOp: $R4=$R4+1

Goto: loop

StrCpy $R1 "$R2" () ($R4)

Pop: $R5

Pop: $R4

Pop: $R3

Pop: $R2

Exch($R1,0)

FunctionEnd

!insertmacro: end of StrStr

Function: "Trim"

Exch($R1,0)

Push: $R2

StrCpy $R2 "$R1" (1) (-1)

StrCmp "$R2" " " equal=RTrim, nonequal=

StrCmp "$R2" "

" equal=RTrim, nonequal=

StrCmp "$R2" "
" equal=RTrim, nonequal=

StrCmp "$R2" ";" equal=RTrim, nonequal=

Goto: Done

StrCpy $R1 "$R1" (-1) ()

Goto: Loop

Pop: $R2

Exch($R1,0)

FunctionEnd

Function: "ConditionalAddToRegisty"

Pop: $0

Pop: $1

StrCmp "$0" "" equal=ConditionalAddToRegisty_EmptyString, nonequal=

WriteRegStr: SHCTX\Software\Microsoft\Windows\CurrentVersion\Uninstall\Ultimaker Cura 0.0\$1=$0

DetailPrint: "Set install registry entry: '$1' to '$0'"

FunctionEnd

!include: could not find: "FileAssociation.nsh"

Error in script "F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/project.nsi" on line 542 -- aborting creation process

**Comment by Ghostkeeper** [comment]
> !include: could not find: "FileAssociation.nsh"

There's the problem I suppose. Can you see if you find the file called `F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/FileAssociation.nsh`? Maybe something to do with administrator rights?

**Comment by JithuPG** [comment]
while placing FileAssociation.nsh & CharStrStrip.nsh files into c:/prohramfiles(x86)/NSIS/includes/ 

The package is created as Ultimaker Cura-0.0.0-win64.exe but the installer have only 290KB and while running installer it doesn't copying any files and the installed directory consist only the uninstaller.exe

**Comment by JithuPG** [comment]
nop i can't find F:/nmake_build/cura-build/build/_CPack_Packages/win64/NSIS/FileAssociation.nsh in my dir

**Comment by JithuPG** [comment]
is it would be the reason ?
previously there was issue  and solved it by 
https://github.com/Ultimaker/cura-build/issues/155#issuecomment-479361090

**Comment by Ghostkeeper** [comment]
Yeah that solution of setting CMAKE_PREFIX_PATH to your Arcus directory could definitely be the cause of this.
