### ISSUE TITLE
what is mean with these build  instructions ?

### ISSUE THREAD

**Issue by white-ghost3886** [Ultimaker/cura-build#216]
Hai i'm trying to build cura Application on windows and target to build for  64-bit version everything seems good found in the build instruction but i'm not able to understand these two instructions as mention in the build instruction

For 64-bit builds:

PyQt 5.4 (https://riverbankcomputing.com/software/pyqt/download5, Building PyQt currently fails using MinGW 64-bit)
Install protobuf.wheel found in cura-build-binaries (TODO: create cura-build-binaries repo)
Create empty __init__.py in c:\Python34\Lib\site-packages\google (TODO: make it part of the proto.wheel installation)

what was these instruction meen to be ?

**Comment by JithuPG** [comment]
@white-ghost3886  i hope this will help you https://github.com/Ultimaker/cura-build/issues/155#issuecomment-480473287

**Comment by Ghostkeeper** [comment]
Yeah those instructions were written for code that was never written, and the PyQt instructions were outdated. I've removed all of it here: https://github.com/Ultimaker/cura-build/commit/99a3366a8f7b42a980a03689535cf9acde3c40e1
