### ISSUE TITLE
cura.appdata.xml is missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/cura-build#220]
Please add `cura.appdata.xml` to the AppImage so that Cura can be shown using its metadata in directories like https://appimage.github.io/Cura/. Thanks.

Reference:
https://docs.appimage.org/packaging-guide/appstream.html

**Comment by probonopd** [comment]
Thank you. The screenshot is over 1 MB in size, maybe it could be compressed a bit more.

**Comment by Ghostkeeper** [comment]
Yeah, I'll run it through optipng. Downloading 1MB shouldn't really be an issue any more in this day and age I think, but it'll depend on how the client wants to show this data.
