### ISSUE TITLE
export VERSION=... before runnnig appimagetool

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/cura-build#224]
Please `export VERSION=...` before runnnig `appimagetool`.

https://github.com/Ultimaker/cura-build/blob/e5e52c0a171ccae0319607667408c968f402eddd/packaging/linux.cmake#L69

This will allow the Cura version to be displayed correctly by tools like appimaged, AppImageLauncher, and many others.

**Comment by probonopd** [comment]
Probably something along the lines of

```
COMMAND export VERSION=$CURA_VERSION_MAJOR.$CURA_VERSION_MINOR.$CURA_VERSION_PATCH
```

would do.

**Comment by probonopd** [comment]
To test that it has worked:

me@host:~$ ./Cura*-x86_64.AppImage --appimage-extract '*.desktop'
squashfs-root/cura.desktop

me@host:~$ cat squashfs-root/cura.desktop 
[Desktop Entry]
(...)
X-AppImage-Version=4.1.99
```

**Comment by LipuFei** [comment]
Hi @probonopd , I tried your approach with this commit 03b3156af92586e2e4c9f199a4995e956c8800eb but it doesn't automatically add the `X-AppImage-Version` field. I have updated our AppImageKit to version 12. Do you know why? And is there a documentation page for those information? Thanks.

**Comment by probonopd** [comment]
I think you are missing `export`.

**Comment by LipuFei** [comment]
I'm using `VERSION=1.2.3 appimagetool ...`, which should be the same as using `export` like below, right?
```
export VERSION=1.2.3
appimagetool ...
```

**Comment by LipuFei** [comment]
BTW, another small remark about the `VERSION` environment variable. I found it too generic. Any application can decide to use a `VERSION` environment variable and interpret it in different ways. Adding a prefix such as `APPIMAGE_` could be a better idea.

**Comment by LipuFei** [comment]
Hi @probonopd , so I tried 3 approaches, but none of them works. I'll do this with the CMake template then.

```
# Approach 1: NOT WORKING
VERSION=1.2.3 appimagetool ...

# Approach 2: NOT WORKING
env VERSION=1.2.3 appimagetool ...

# Approach 3: NOT WORKING
export VERSION=1.2.3
appimagetool ...
```

**Comment by LipuFei** [comment]
Done in ec72bcd9c6e8e39c4e23e508613922c3d28cef3f

**Comment by probonopd** [comment]
Thank you @LipuFei highly appreciated :+1:

**Comment by probonopd** [comment]
I see you are using Docker, so maybe you'd need to use

```
ENV VERSION 1.2.3
```

Also see https://vsupalov.com/docker-arg-env-variable-guide/.

**Comment by thopiekar** [comment]
Well, if it was my decision at this point I would never apply variables which such common names globally. Who knows what the impact is.
If that one is only needed on the AppImage creation level, then this variable should be only available there.
So what @LipuFei decided on, is just perfect 👍

**Comment by probonopd** [comment]
Agree, that's a good working solution :+1:

**Comment by LipuFei** [comment]
> 
> 
> I see you are using Docker, so maybe you'd need to use
> 
> ```
> ENV VERSION 1.2.3
> ```
> 
> Also see https://vsupalov.com/docker-arg-env-variable-guide/.

I also tried it on our build server, which doesn't use docker. Unfortunately, setting the `VERSION` variable still didn't work.

**Comment by probonopd** [comment]
Thanks for letting me know. I don't really have Docker experience, but I think the solution you have now will work just fine. Thank you.
