### ISSUE TITLE
Build fails on Windows due to space not escaped in path

### ISSUE THREAD

**Issue by dawzon** [Ultimaker/cura-build#245]
I ran into an error where my build failed with the following error, while running `mingw32-make`:
I'm using Windows 10.
```
[ 12%] Performing build step for 'CuraEngine'
cd /d C:\Users\dcoleman\Desktop\cura-build\build\CuraEngine-prefix\src\CuraEngine-build && C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/mingw32-make
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make[2]: *** [CMakeFiles\CuraEngine.dir\build.make:132: CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/dcoleman/Desktop/cura-build/build'
mingw32-make[1]: *** [CMakeFiles\Makefile2:265: CMakeFiles/CuraEngine.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/dcoleman/Desktop/cura-build/build'
mingw32-make: *** [Makefile:151: all] Error 2
```
(I used the -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMake option in order to show the actual commands)

It appears that the path is not being escaped properly to account for the space in "Program Files".  This causes issues with the default installation path for minGW-W64, which is under C:\Program Files\.

As a workaround, installing minGW at a location that doesn't have a space in the path seems to solve the issue.

**Comment by Ghostkeeper** [comment]
I found a few spots where quotes were missing. Could you try again? It still works on my end, but I didn't have the problem in the first place.

And if not, could you share the `CMakeFiles\CuraEngine.dir\build.make` file that it generates for you?

**Comment by dawzon** [comment]
That fixes the issue for me.  Thanks!
