### ISSUE TITLE
Running "make package" does nothing

### ISSUE THREAD

**Issue by dawzon** [Ultimaker/cura-build#246]
I'm trying to follow the guide for building from source.  Compiling cura itself works (All the files are present and working in /build/package), but I'm having trouble generating the installer files.  The readme says to run `mingw32-make package`, but when I do that I get `mingw32-make: Nothing to be done for 'package'`.  Am I missing something?

I used the argument -DSIGN_PACKAGE:BOOL=OFF with cmake, if that makes any difference.

(As an aside, I also noticed `package` isn't listed by the output of `mingw32-make help`)

**Comment by Ghostkeeper** [comment]
Ah yeah I see. The target is called `packaging`, not `package`. It's also included with the all-target. However you do need to have `BUILD_PACKAGE=ON`, which is the default.

I'll correct the readme. Wonder how long this has been inconsistent...

**Comment by dawzon** [comment]
Ah, that makes more sense.  However, for some reason I'm still having issues generating the installer.  After I run the all target I have the all the expected files in package/ but I can't seem to find any installer .exe or .msi in the build directory.

This is the output from what appears to be the packaging step.  It looks like the installer just isn't being created?  NSIS and WIX Toolset should both be on my path.
```
[ 97%] Built target build_bundle
mingw32-make  -f CMakeFiles\packaging.dir\build.make CMakeFiles/packaging.dir/depend
mingw32-make[3]: Entering directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Users\dcoleman\Desktop\cura_master\cura-build C:\Users\dcoleman\Desktop\cura_master\cura-build C:\Users\dcoleman\Desktop\cura_master\cura-build\build C:\Users\dcoleman\Desktop\cura_master\cura-build\build C:\Users\dcoleman\Desktop\cura_master\cura-build\build\CMakeFiles\packaging.dir\DependInfo.cmake --color=
Scanning dependencies of target packaging
mingw32-make[3]: Leaving directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
mingw32-make  -f CMakeFiles\packaging.dir\build.make CMakeFiles/packaging.dir/build
mingw32-make[3]: Entering directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
[100%] Packaging Projects...
mingw32-make[3]: Leaving directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
[100%] Built target packaging
mingw32-make[2]: Leaving directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\dcoleman\Desktop\cura_master\cura-build\build\CMakeFiles 0
mingw32-make[1]: Leaving directory 'C:/Users/dcoleman/Desktop/cura_master/cura-build/build'
```

**Comment by Ghostkeeper** [comment]
Hmm, yeah that's weird.

You can see that it's executing the `packaging` target, since it's commenting with `Packaging Projects...`. For you on Windows it should include [this CMake script](https://github.com/Ultimaker/cura-build/blob/master/packaging/windows.cmake) that defines an additional target on which `packaging` depends: `build_bundle`. This target has several commands attached to it, each with their comments to show progress. Among those are `running cx_Freeze...` which I don't see in that snippet of your output.

I don't understand why it wouldn't run those commands on your computer though. It would need some real debugging.
