### ISSUE TITLE
missing "`" in build.ps1

### ISSUE THREAD

**Issue by AmrBarghouthi** [Ultimaker/cura-build#250]
https://github.com/Ultimaker/cura-build/blob/3cb5400dae820b605b822895294bfe0a587b088a/scripts/python3.5/windows/build.ps1#L126

this line needs a "`"

Regards

**Comment by AmrBarghouthi** [comment]
apparently solved by my brother in #249

**Comment by Ghostkeeper** [comment]
Goes to show how badly tested this really is. We haven't been using the Windows docker image in a year or so.

**Comment by Ghostkeeper** [comment]
Corrected now by your brother.
