### ISSUE TITLE
Compile failed on docker image win1809-latest tag

### ISSUE THREAD

**Issue by hongliang5316** [Ultimaker/cura-build#253]
```bash
 .\scripts\python3.5\windows\build.ps1
```

report errors:
========== Build Variables END ==========
Prepare environment variables ...
Prepare work directory "C:\temp\cura-build" ...
"Copying C:\cura-build-src to C:\temp\cura-build"
A subdirectory or file C:\cura-build-output\build already exists.
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/cura-build-output/build/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_700d1\fast &&       "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
BIN\amd64\nmake.exe"  -f CMakeFiles\cmTC_700d1.dir\build.make /nologo -L                  CMakeFiles\cmTC_700d1.dir\buil
d
    Building C object CMakeFiles/cmTC_700d1.dir/testCCompiler.c.obj
        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" @C:\Users\ContainerAdministrator\AppDa
ta\Local\Temp\nm2337.tmp
    testCCompiler.c
    Linking C executable cmTC_700d1.exe
        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_700d1.dir --rc="C:\Program Files
(x86)\Windows Kits\8.1\bin\x64\rc.exe" --mt="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\mt.exe" --manifests  -- "C:
\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\link.exe" /nologo @CMakeFiles\cmTC_700d1.dir\objects1.rsp
 @C:\Users\ContainerAdministrator\AppData\Local\Temp\nm24A0.tmp
    LINK Pass 1: command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\
cmTC_700d1.dir\objects1.rsp /out:cmTC_700d1.exe /implib:cmTC_700d1.lib /pdb:C:\cura-build-output\build\CMakeFiles\CMakeT
mp\cmTC_700d1.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib win
spool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_
700d1.dir/intermediate.manifest CMakeFiles\cmTC_700d1.dir/manifest.res" failed (exit code 1318) with the following outpu
t:
    LINK : fatal error LNK1318: Unexpected PDB error; UNKNOWN (24) '?'
    NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return c
ode '0x2'
    Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

-- Configuring incomplete, errors occurred!
See also "C:/cura-build-output/build/CMakeFiles/CMakeOutput.log".
See also "C:/cura-build-output/build/CMakeFiles/CMakeError.log".

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'package'
Stop.
Copying the installer to the mounted volume ...
Ultimaker_Cura*.exe
The system cannot find the file specified.
        0 file(s) copied.
Ultimaker_Cura*.msi
The system cannot find the file specified.
        0 file(s) copied.

**Comment by Ghostkeeper** [comment]
Handy, Docker! It behaves always the same on all computers so you can deploy from anywhere! /s

I don't know how to reproduce your error. Our CI server doesn't get it in any case. I tried looking up the error code and came upon this possible workaround: https://stackoverflow.com/questions/61992700/fatal-error-lnk1318-unexpected-pdb-error-format-11
So I suppose that deleting the file `C:\cura-build-output\build\CMakeFiles\CMakeT
mp\cmTC_700d1.pdb` might allow it to continue. Or perhaps it's just hitting a corrupt part of your hard disk or something and just re-running the current script from a fresh image helps.

**Comment by gaoglegao** [comment]
> Handy, Docker! It behaves always the same on all computers so you can build from anywhere! /s
> 
> I don't know how to reproduce your error. Our CI server doesn't get it in any case. I tried looking up the error code and came upon this possible workaround: https://stackoverflow.com/questions/61992700/fatal-error-lnk1318-unexpected-pdb-error-format-11
> So I suppose that deleting the file `C:\cura-build-output\build\CMakeFiles\CMakeTemp\cmTC_700d1.pdb` might allow it to continue. Or perhaps it's just hitting a corrupt part of your hard disk or something and just re-running the current script from a fresh image helps.

i got the same problem........

**Comment by gaoglegao** [comment]
> Handy, Docker! It behaves always the same on all computers so you can build from anywhere! /s
> 
> I don't know how to reproduce your error. Our CI server doesn't get it in any case. I tried looking up the error code and came upon this possible workaround: https://stackoverflow.com/questions/61992700/fatal-error-lnk1318-unexpected-pdb-error-format-11
> So I suppose that deleting the file `C:\cura-build-output\build\CMakeFiles\CMakeTemp\cmTC_700d1.pdb` might allow it to continue. Or perhaps it's just hitting a corrupt part of your hard disk or something and just re-running the current script from a fresh image helps.

Do not use your CI server ,try it in a PC,you will get it quickly,and there is no "cmTC_700d1.pdb" file in the path.

**Comment by evtrados** [comment]
Although I am not 100% sure if this is the source of the issue, be aware that on Windows docker images, even Microsoft mentions that the host OS version of Windows needs to be the same as the one of the docker image/container you will use (please refer to section 'How to use this image' in https://hub.docker.com/_/microsoft-windows-servercore). 
For instance, we've been having some test builds using the windows servercore 1809 docker image, but for that to work locally you'll need a Windows PC/laptop/Server with the same version. Since most PCs have by now surpassed this version by far (most new Windows PCs will now be at version `20H2`) the best chances you will have to get this working is to use a newer servercore docker image that is the same as your host PC. You have to note though that this is totally untested and uncharted territory, as you might face different issues (e.g., not being able to install Visual Studio 2015 at all, etc).
From what I've tried though, this error you're getting is usually encountered whenever my host OS version is different from that of the target docker image.
Good luck!
