### ISSUE TITLE
How to make installer with NSIS

### ISSUE THREAD

**Issue by alexwoo1900** [Ultimaker/cura-build#261]
**Environment**

Windows 10 64-bit

**Target**

Cura 4.10.0

**What I have done**

I followed the instructions in README and built all the parts into build\package. The executable file works well.

**Question**

I noticed that the project did not generate the installer for me but there is a arduino folder in build\inst. Do the scripts in cura-build provide automated installer-making services for us? If so, how to make it enabled?

**Comment by alexwoo1900** [comment]
Solved.

**Comment by Ghostkeeper** [comment]
Maybe you'd like to share, for posterity, what the problem was you encountered, and how you solved it?

The CMake script is expected to generate an installer at the end automatically, on Windows.

**Comment by alexwoo1900** [comment]
@Ghostkeeper 

Yes. The script contains instructions to generate the installer.
But if someone just enters the command "mingw32-make" like README did, the packaged part will not be activated.
I found out the answer in docker script. The action word "package" or "all" is necessary.

mingw32-make package

I think the cura team needs to update cura-build & cura-build-environment guide.

**Comment by Ghostkeeper** [comment]
Indeed, that was incorrect. Thanks for the correction!
