### ISSUE TITLE
"No such DSL method 'node_names' found among steps" using Jenkins

### ISSUE THREAD

**Issue by kpochwala** [Ultimaker/cura-build#267]
Hello, I want to set up Cura CI for Jenkins learning purpose, however I'm getting an error:

No such DSL method 'node_names' found among steps

I've set up job as Pipeline project and the Jenkinsfile is read correctly. I suppose that I might be missing some plugin - I'd be grateful for any hints.

**Comment by Ghostkeeper** [comment]
Did you close this because you found a solution? If so, it would help the community to share the solution with others.

Although I think this has more to do with Jenkins than with Cura. Nodes sounds like the machines the tests are being ran on.

**Comment by Ghostkeeper** [comment]
See https://github.com/Ultimaker/cura-build-environment/issues/111.
