### ISSUE TITLE
Confusing file paths and files not found

### ISSUE THREAD

**Issue by efischer-g3d** [Ultimaker/cura-build#271]
I'm trying to build Cura using the Docker container from cura-build-environment and I'm confused on a couple things

- `.\scripts\python3.5\windows\build.ps1` Is this the file that is located in `docker/windows/build.ps1`?
- `C:\cura-build-src\scripts\python3.8\windows\build_in_docker_vs2015.cmd` is referenced in `docker/windows/build.ps1` and there is a `vs2019` matching file in `docker/windows/` is that the one that should be referenced? 
- Is the path `C:\cura-build-src` looking at the docker container? A folder of that name doesn't seem to exist anywhere either

**Comment by Ghostkeeper** [comment]
Thanks for the report! The documentation was indeed outdated. We should not forget to update that, when updating the paths of these scripts.

> Is the path `C:\cura-build-src` looking at the docker container?

It's a path inside the Docker container, indeed.
