### ISSUE TITLE
Unable to locate package qml-module's

### ISSUE THREAD

**Issue by peteruithoven** [Ultimaker/cura-build#28]
I'm trying to build Cura on Elementary OS (based on Ubuntu 14.04 LTS), but I it can't find the qml-module... packages. The other packages are installed. 

Is there a certain ppa I need to add? Should I install the [Qt Online Installer for Linux](http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run)? Are they included into other packages, like `qtdeclarative-opensource-src`?

**Comment by peteruithoven** [comment]
Still not sure why those qml modules are listed, but I've done a pull request to add the remaining packages that I needed to install to build:
https://github.com/Ultimaker/cura-build/pull/31

**Comment by Ghostkeeper** [comment]
Thanks. I don't think any of us developers have any experience with Elementary.
