### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by CoDanny** [Ultimaker/cura-build#3]
Mac OSX 10.10.3

I cloned this directory and run:

```
 cmake .
 make
```

I get the following error:

```
CMake Error at scripts/ECMPoQmTools.cmake:142 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

   Qt5LinguistToolsConfig.cmake
   qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:61 (ecm_process_po_files_as_qm)
```

**Comment by awhiemstra** [comment]
Can you provide the full command line output? Kinda hard to find out which project fails from just the error message.

**Comment by CoDanny** [comment]
Kinda long but here you go:

Daniels-MacBook-Pro:cura-build arroyo$ make 
[  1%] Performing update step for 'Protobuf'
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[  2%] Performing configure step for 'Protobuf'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arroyo/3dagogo-repos/Cura/cura-build/Protobuf-prefix/src/Protobuf-build
[  3%] Performing build step for 'Protobuf'
[ 48%] Built target libprotoc
[ 84%] Built target protobuf
[ 99%] Built target protobuf-lite
[100%] Built target protoc
[  4%] Performing install step for 'Protobuf'
[ 48%] Built target libprotoc
[ 84%] Built target protobuf
[ 99%] Built target protobuf-lite
[100%] Built target protoc
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/bin/protoc
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/liblibprotoc.a
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf.a(atomicops_internals_x86_msvc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf.a(gzip_stream.cc.o) has no symbols
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf-lite.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf-lite.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libprotobuf-lite.a(atomicops_internals_x86_msvc.cc.o) has no symbols
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomic_sequence_num.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_aix.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_arm_gcc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_arm_qnx.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_atomicword_compat.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_macosx.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_mips_gcc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_pnacl.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_solaris.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_tsan.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_x86_gcc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/atomicops_internals_x86_msvc.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/casts.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/common.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/fastmem.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/hash.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/once.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/platform_macros.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/shared_ptr.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/singleton.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/stl_util.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/template_util.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/stubs/type_traits.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/arena.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/arenastring.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/descriptor_database.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/descriptor.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/descriptor.pb.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/dynamic_message.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/extension_set.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/generated_enum_reflection.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/generated_enum_util.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/generated_message_reflection.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/generated_message_util.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_entry.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_entry_lite.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_field.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_field_lite.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_field_inl.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/map_type_handler.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/message.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/message_lite.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/metadata.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/reflection.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/reflection_ops.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/repeated_field.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/repeated_field_reflection.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/service.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/text_format.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/unknown_field_set.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/wire_format.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/wire_format_lite.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/wire_format_lite_inl.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/coded_stream.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/printer.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/strtod.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/tokenizer.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/zero_copy_stream.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/zero_copy_stream_impl.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/io/zero_copy_stream_impl_lite.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/code_generator.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/command_line_interface.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/importer.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/parser.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/plugin.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/plugin.pb.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/cpp/cpp_generator.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/java/java_generator.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/java/java_names.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/javanano/javanano_generator.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/python/python_generator.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/google/protobuf/compiler/ruby/ruby_generator.h
[  5%] Completed 'Protobuf'
[  8%] Built target Protobuf
[ 16%] Built target Python
[ 17%] Performing update step for 'Arcus'
Already on '15.06'
Your branch is up-to-date with 'origin/15.06'.
[ 18%] Performing configure step for 'Arcus'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arroyo/3dagogo-repos/Cura/cura-build/Arcus-prefix/src/Arcus-build
[ 19%] Performing build step for 'Arcus'
[ 33%] Built target Arcus
Linking CXX executable example
[100%] Built target example
[ 20%] Performing install step for 'Arcus'
[ 33%] Built target Arcus
[100%] Built target example
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/libArcus.a
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/Arcus/Socket.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/Arcus/SocketListener.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/Arcus/Types.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/include/Arcus/ArcusExport.h
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/cmake/Arcus/Arcus-targets.cmake
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/cmake/Arcus/Arcus-targets-release.cmake
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/cmake/Arcus/ArcusConfig.cmake
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/cmake/Arcus/ArcusConfigVersion.cmake
-- Up-to-date: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/lib/python3.4/site-packages/Arcus/__init__.py
[ 20%] Completed 'Arcus'
[ 23%] Built target Arcus
[ 24%] Performing update step for 'CuraEngine'
Already on '15.06'
Your branch is behind 'origin/15.06' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[ 25%] Performing configure step for 'CuraEngine'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arroyo/3dagogo-repos/Cura/cura-build/CuraEngine-prefix/src/CuraEngine-build
[ 26%] Performing build step for 'CuraEngine'
[  3%] Built target clipper
Linking CXX executable CuraEngine
[100%] Built target CuraEngine
[ 27%] Performing install step for 'CuraEngine'
[  3%] Built target clipper
[100%] Built target CuraEngine
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/arroyo/3dagogo-repos/Cura/cura-build/inst/bin/CuraEngine
[ 28%] Completed 'CuraEngine'
[ 30%] Built target CuraEngine
[ 38%] Built target Sip
[ 45%] Built target Qt
[ 52%] Built target PyQt
[ 53%] Performing update step for 'Uranium'
Already on '15.06'
Your branch is up-to-date with 'origin/15.06'.
[ 54%] Performing configure step for 'Uranium'
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Error at scripts/ECMPoQmTools.cmake:142 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:61 (ecm_process_po_files_as_qm)


-- Configuring incomplete, errors occurred!
See also "/Users/arroyo/3dagogo-repos/Cura/cura-build/Uranium-prefix/src/Uranium-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [Uranium-prefix/src/Uranium-stamp/Uranium-configure] Error 1
make[1]: *** [CMakeFiles/Uranium.dir/all] Error 2
make: *** [all] Error 2

**Comment by awhiemstra** [comment]
I realised Friday that this is due to Uranium's CMake files just checking for gettext - apparently CMake picks that up from somewhere on your system. Adding an additional check for Qt5LinguistTools should fix it, I will try and get that in today.

**Comment by nickthetait** [comment]
:+1: I was getting this same "Qt5LinguistTools" error on Debian.
