### ISSUE TITLE
Python-OpenGL requirement on Ubuntu/Linux

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build#34]
Since I created a alternative fix for Cura using nvidia drivers, is Python3-OpenGL still needed?

**Comment by nallath** [comment]
@awhiemstra Build system is your thing :)

**Comment by macaddr** [comment]
I think ,you'd better install it.

**Comment by thopiekar** [comment]
@macaddr: Why? The only part of the code, which was using the OpenGL
module, has been replaced with a generic code, which is doing the same as
the code before.

So no need for the module anymore (as I beleave it was the only place where
it was needed) (Nvidia workaround).

**Comment by macaddr** [comment]
@thopiekar 
I thought you would never solve the dependency .

It looks like I'm more than a concern.
