### ISSUE TITLE
make error on win8.1

### ISSUE THREAD

**Issue by 18504141418** [Ultimaker/cura-build#43]
I have done everyting about this cura-build.when I get close to the success,the cmd tell me error
-- Installing: C:/Users/kk-pc/Desktop/cura-build-master/build/inst/./arduino/ard
uino.cat
-- Installing: C:/Users/kk-pc/Desktop/cura-build-master/build/inst/./arduino/ard
uino.inf
-- Installing: C:/Users/kk-pc/Desktop/cura-build-master/build/inst/./arduino/dpi
nst32.exe
-- Installing: C:/Users/kk-pc/Desktop/cura-build-master/build/inst/./arduino/dpi
nst64.exe
[100%] Completed 'cura-binary-data'
[100%] Built target cura-binary-data
Scanning dependencies of target build_exe
Running py2exe
Traceback (most recent call last):
  File "setup_win32.py", line 13, in <module>
    import Arcus
ImportError: No module named 'Arcus'
CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
mingw32-make[2]: *** [build_exe] Error 1
CMakeFiles\Makefile2:526: recipe for target 'CMakeFiles/build_exe.dir/all' faile
d
mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

I got 100%,but it tell me error .I don't how to make it

**Comment by nallath** [comment]
Look through some of the other issues. This one was posted before.
