### ISSUE TITLE
Build on ubuntu 16.04

### ISSUE THREAD

**Issue by kenjo** [Ultimaker/cura-build#57]
So I have runtime error. 

Traceback (most recent call last):
  File "/opt/cura/bin/cura", line 19, in <module>
    import cura.CuraApplication
  File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 29, in <module>
    from . import PlatformPhysics
  File "/opt/cura/lib/python3/dist-packages/cura/PlatformPhysics.py", line 17, in <module>
    from . import ConvexHullJob
  File "/opt/cura/lib/python3/dist-packages/cura/ConvexHullJob.py", line 6, in <module>
    from UM.Math.Polygon import Polygon
  File "/opt/cura/lib/python3/dist-packages/UM/Math/Polygon.py", line 12, in <module>
    import scipy.spatial
  File "/opt/cura/lib/python3/dist-packages/scipy/spatial/__init__.py", line 91, in <module>
    from .ckdtree import *
  File "__init__.pxd", line 155, in init ckdtree (scipy/spatial/ckdtree/ckdtree.cxx:22466)
ValueError: numpy.dtype has the wrong size, try recompiling

I did have to do some small changes to build but I do not think that is the problem. 
here is the changes I did. 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 76835f5..4d1d7a9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -81,7 +81,7 @@ set(EXTERNALPROJECT_SITEPACKAGES_DIR ${EXTERNALPROJECT_INSTALL_PREFIX}/lib/pytho
 if(DEFINED ENV{CURA_MAJOR_VERSION})
     set(CURA_MAJOR_VERSION $ENV{CURA_MAJOR_VERSION} CACHE STRING "Cura Major Version" FORCE)
 else()
-    set(CURA_MAJOR_VERSION "master" CACHE STRING "Cura Major Version")
+    set(CURA_MAJOR_VERSION "2" CACHE STRING "Cura Major Version")
 endif()
 
 if(DEFINED ENV{CURA_MINOR_VERSION})
@@ -570,7 +570,7 @@ elseif(BUILD_OS_LINUX)
         "${CMAKE_COMMAND} -E make_directory ${package_dir}/usr/share/applications"
         "${CMAKE_COMMAND} -E copy ${CMAKE_SOURCE_DIR}/cura ${package_dir}/usr/bin/"
         "${CMAKE_COMMAND} -E copy ${CMAKE_SOURCE_DIR}/cura.desktop ${package_dir}/usr/share/applications/"
-        "${CMAKE_COMMAND} -E copy /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20 ${package_dir}/opt/cura/lib/libstdc++.so.6"
+        "${CMAKE_COMMAND} -E copy /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21 ${package_dir}/opt/cura/lib/libstdc++.so.6"
     )
 endif()
 
@@ -600,7 +600,6 @@ set(CPACK_RPM_PACKAGE_RELOCATABLE OFF)
 
 set(DEB_DEPENDS
     "python3 (>= 3.4.0)"
-    "python3 (<< 3.5.0)"
     "python3-opengl (>= 3.0)"
     "libgfortran3"
 )

```

**Comment by thopiekar** [comment]
Related to a discussion at https://github.com/Ultimaker/cura-build/pull/54

**Comment by kenjo** [comment]
Well I'am building from source against python 3.5 so scipy really should not have any problems. Don't know why it's complaining. I do not have any other version on my system only the one that cura-build has downloaded and compiled.

**Comment by thopiekar** [comment]
Well, in different places it is hardcoded. For example the cura.desktop file calls ```python3.4``` even if there is no python 3.4 installed. Additionally there are some changes in Python3.5 which break compatibility with Numpy, so for 3.5 you'll need a more recent version. It is more complicated then you think.
In short that's the reason why I build packages of Cura and its dependencies in separate packages. So the patches I made here recently, are just made in relation with other pull request or they are just simple corrections which I found during some investigations.

However, if you are using Ubuntu Xenial I personally recommend to use my PPA. It works very well so far and as long as I use Cura for my printer I will always take care about the PPA's, too. But don't forget to mention when reporting bugs that you are using my PPA. Probably it will be easier to find problems :wink: 

* https://launchpad.net/~thopiekar/+archive/ubuntu/cura

**Comment by kenjo** [comment]
I prefer to build myself as I plan to do some changes. But if the cura-build is not going to work I need to build against the system provided versions. I did try to update the scipy from 0.16.1 to 0.17.0 but still same problem.

I guess I can adopt ubuntu-15.04-build-script.sh  to work with 16.04.

**Comment by thopiekar** [comment]
You can always gain root-rights and modify the code. My packages don't use
any python binaries like all the other modules provided in the
Ubuntu/Debian repositories.
Additionally you also use apt-get source <package_name>, do you changes and
rebuild it locally for testing. Finally you can sync your changes with your
Got repository and send patches ;)

But you can also work your way, that's no problem :)

**Comment by kenjo** [comment]
well I'm starting to develop a strong distaste for python. Well at least the dependencies.
I'm not succeeding in compiling libarcus.

I wanted to compile and install cura into its own directory but Things really do not want to play along.
```
#!/bin/bash

INSTALL_DIR=$(pwd)/install

prepare() {
    mkdir $INSTALL_DIR
    
    sudo apt-get install -y git cmake cmake-gui autoconf libtool python3-setuptools curl python3-pyqt5.* python3-numpy qml-module-qtquick-controls sip-dev
    git clone https://github.com/Ultimaker/Cura.git
    git clone https://github.com/Ultimaker/Uranium.git
    git clone https://github.com/Ultimaker/CuraEngine.git
    git clone https://github.com/Ultimaker/libArcus
    git clone https://github.com/Ultimaker/protobuf.git

    (
	cd protobuf
	patch -p1 < ../ubuntu-16.04_protobuf.patch
    )
    (
	cd libArcus
	patch -p1 < ../ubuntu-16.04_libarcus.patch
    )
    
}

bc_protobuf() {
    mkdir build_protobuf
    (
	cd build_protobuf
	cmake ../protobuf -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
	make -j8 
	make install
    )
}

b_protobuf() {
    mkdir build_protobuf
    (
	cd protobuf
	./autogen.sh
    )
    (
	#cd build_protobuf
	cd protobuf
	../protobuf/configure --prefix=$INSTALL_DIR --enable-silent-rules
	make -j8
	make install
    )
    echo "-------------------------------------------------------------------------------"
    (
	cd protobuf/python
	python setup.py build --cpp_implementation 
	#python setup.py google_test --cpp_implementation
	python setup.py install --prefix=$INSTALL_DIR
    )
}

b_libarcus() {
    mkdir build_libarcus
    (
	cd build_libarcus
	cmake ../libArcus/ -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR  -DSIP_INCLUDE_DIR_EXTRA:STRING=/usr/include/python2.7  -DPYTHON_SITE_PACKAGES_DIR=$INSTALL_DIR/lib/python3/dist-packages
	# cmake ../libArcus/ -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR  -DPYTHON_SITE_PACKAGES_DIR=$INSTALL_DIR/lib/python3/dist-packages
	make VERBOSE=1
	make install 
    )
}

export PATH=$INSTALL_DIR/bin:$PATH
prepare
b_protobuf
b_libarcus

```
ubuntu-16.04_libarcus.patch
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 448ec87..8ced865 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -20,7 +20,7 @@ if(BUILD_PYTHON)
         set(PYTHON_SITE_PACKAGES_DIR lib/python3/dist-packages CACHE STRING "Directory to install Python bindings to")
     endif()
     find_package(SIP REQUIRED)
-    include_directories(python/ src/ ${PYTHON_INCLUDE_DIR} ${SIP_INCLUDE_DIR})
+    include_directories(python/ src/ ${PYTHON_INCLUDE_DIR} ${SIP_INCLUDE_DIR} ${SIP_INCLUDE_DIR_EXTRA})
 endif()
 
 if(NOT ${CMAKE_VERSION} VERSION_LESS 3.1)

```

ubuntu-16.04_protobuf.patch

```
diff --git a/python/setup.py b/python/setup.py
index 1f0db93..91f1ffd 100755
--- a/python/setup.py
+++ b/python/setup.py
@@ -156,9 +156,9 @@ if __name__ == '__main__':
           "google/protobuf/pyext/repeated_scalar_container.cc",
           "google/protobuf/pyext/repeated_composite_container.cc" ],
         define_macros=[('GOOGLE_PROTOBUF_HAS_ONEOF', '1')],
-        include_dirs = [ ".", "..", "../src"],
+        include_dirs = [ ".", "..", "../src","../../install/include"],
         libraries = [ "protobuf" ],
-        library_dirs = [ '../src/.libs' ],
+        library_dirs = [ '../src/.libs',"../../install/lib" ],
         ))
     os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'cpp'
 


```

**Comment by Ghostkeeper** [comment]
>well I'm starting to develop a strong distaste for python. Well at least the dependencies.

I'm developing a taste for Python. But I agree with you on the dependencies... You'd think there are better ways.

>I'm not succeeding in compiling libarcus.

What errors are you getting now when compiling Arcus then?

**Comment by kenjo** [comment]
[ 72%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o
/usr/bin/c++   -Dpython_module_Arcus_EXPORTS -I/home/kenjo/proj/3dprint/cura/libArcus/python -I/home/kenjo/proj/3dprint/cura/libArcus/src -I/usr/include/python3.5m -I/usr/include/python2.7 -I/home/kenjo/proj/3dprint/cura/install/include  -static-libstdc++ -fPIC   -std=gnu++11 -o CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o -c /home/kenjo/proj/3dprint/cura/libArcus/python/PythonMessage.cpp
In file included from /home/kenjo/proj/3dprint/cura/libArcus/python/PythonMessage.cpp:24:0:
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:37: error: ‘is_proto_enum’ was not declared in this scope
     T, typename internal::enable_if<is_proto_enum<T>::value>::type> {
                                     ^
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:52: error: template argument 1 is invalid
     T, typename internal::enable_if<is_proto_enum<T>::value>::type> {
                                                    ^
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:60: error: expected ‘(’ before ‘>’ token
     T, typename internal::enable_if<is_proto_enum<T>::value>::type> {
                                                            ^
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:60: error: template argument 2 is invalid
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:63: error: expected ‘{’ or ‘:’ before ‘type’
     T, typename internal::enable_if<is_proto_enum<T>::value>::type> {
                                                               ^
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:63: error: expected ‘{’ before ‘type’
/home/kenjo/proj/3dprint/cura/install/include/google/protobuf/reflection.h:539:67: error: expected initializer before ‘>’ token
     T, typename internal::enable_if<is_proto_enum<T>::value>::type> {
                                                                   ^
CMakeFiles/python_module_Arcus.dir/build.make:285: recipe for target 'CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o' failed
make[2]: *** [CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o] Error 1
make[2]: Leaving directory '/home/kenjo/proj/3dprint/cura/build_libarcus'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/python_module_Arcus.dir/all' failed
make[1]: *** [CMakeFiles/python_module_Arcus.dir/all] Error 2
make[1]: Leaving directory '/home/kenjo/proj/3dprint/cura/build_libarcus'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kenjo** [comment]
And yes its finding the protobuf I installed 
-- Found Protobuf: /home/kenjo/proj/3dprint/cura/install/lib/libprotobuf.so (Required is at least version "3.0.0")

**Comment by lolorc** [comment]
encountering the same issue trying to compile cura for ubuntu 16.10.
I wouldn't say it's entirely python's fault...

**Comment by thopiekar** [comment]
Hey @kenjo,
don't believe everything that CMake says here. Well, yes, it probably found Protobuf, but haven't found the protobuf headers (for example) :wink: 

@lolorc Why are you trying to build Cura via cura-build?
There is a PPA and an AppImage available and you could invest your time in pushing your changes directly into Cura, Uranium or whatever :wink:

**Comment by lolorc** [comment]
@thopiekar oh is there an official repository ? looks like I missed that on the official web page.

**Comment by lolorc** [comment]
looks like it's not an official repository, that makes me wonder why all the work you've done can't reach upstream. Also I'm wondering why do you discourage user from compiling upstream and tell them to install untrusted binaries instead. I'll have a look at the appimage blob, thanks for the hint.

**Comment by thopiekar** [comment]
No problem.
Well, as long as you don't share your ideas, we can't decide whether these changes can go upstream or not :wink: 
Well, if you mean by official PPA a PPA supported by Ultimaker, then no. You probably noticed that I'm the maintainer of the PPA and I work with the PPA everyday. The packages are built right from the branches here on GitHub, so in theory you are even getting bug fixes much earlier (with risk that these might break something, if they were work in progress of course).
Don't know which benefits you see behind an company driven PPA or whatever you mean by "official PPA", but if Ultimaker itself recommends my PPA on problems (see their PPA), my PPA probably can't be so bad, isn't it? :smile:

**Comment by peteruithoven** [comment]
That ppa (and app image) sound awesome. I too can't find that on the Cura website, where can I find more information?

**Comment by thopiekar** [comment]
You'll find the AppImage in the Beta section of the download page and for the PPA just google for "Cura PPA". Here it shows my stable PPA as the first result 🙂
But don't forget that there is an issue running Cura on Unity using my PPA due to some hacks Canonical applied to the Qt5 packages.
But other desktops just work fine 👌

**Comment by Ghostkeeper** [comment]
I don't know exactly why Ultimaker doesn't support Thopiekar's PPA, but I can think of a few reasons. In order of likelihood:
* The people higher up don't know about it. It takes the effort of management, marketing, the web design and the Cura teams to set that up.
* They don't consider it worth the effort to maintain by how many people would use it, or nobody has taken the effort to look into if it's worth the effort to maintain.
* Since it builds bleeding-edge unstable versions of Cura, they don't want it to ruin Ultimaker's name by publishing buggy software.

**Comment by lolorc** [comment]
I don't really get why there isn't a PR to implement Thopiekar's build changes into that repository.
That would be the first thing to do.

I've tried the appimage blob, it can't stop segfaulting.
To me Ultimaker's name is quite tainted because of this situation:
- provided packages don't work (outdated dependencies)
- provided appimage crashes (segfaults when loading a stl, or adding kossel mini as new printer)
- unable to build from source
- left with an unofficial ppa with hacks

**Comment by thopiekar** [comment]
> - left with an unofficial ppa with hacks

I added neither a patch nor any hack to my packages: https://github.com/thopiekar/Cura-packaging
If you find anything "hacky" just let me know.

**Comment by lolorc** [comment]
sorry for the moaning/ranting :)
