### ISSUE TITLE
build error:  can't build protobuf-lite

### ISSUE THREAD

**Issue by kcleung** [Ultimaker/cura-build#58]
I am running Ubuntu 16.04, and I have followed the instructions in README, and run cmake ../ and make

However it fails to build protobuf-lite:

-- Build files have been written to: /mnt/hgfs/git/dev/cura-build/build/Protobuf-prefix/src/Protobuf-build
[  5%] Performing build step for 'Protobuf'
Scanning dependencies of target libprotobuf-lite
CMakeFiles/libprotobuf-lite.dir/depend.make:4: **\* missing separator.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libprotobuf-lite.dir/all' failed
make[4]: **\* [CMakeFiles/libprotobuf-lite.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: **\* [all] Error 2
CMakeFiles/Protobuf.dir/build.make:113: recipe for target 'Protobuf-prefix/src/Protobuf-stamp/Protobuf-build' failed
make[2]: **\* [Protobuf-prefix/src/Protobuf-stamp/Protobuf-build] Error 2
CMakeFiles/Makefile2:625: recipe for target 'CMakeFiles/Protobuf.dir/all' failed
make[1]: **\* [CMakeFiles/Protobuf.dir/all] Error 2
Makefile:105: recipe for target 'all' failed
make: **\* [all] Error 2
abc@abc-virtual-machine:/mnt/hgfs/git/dev/cura-build/build$

**Comment by Ghostkeeper** [comment]
I think this is an upstream issue, unless you have a very old version of CMake on your very new version of Ubuntu. Is there any report on https://github.com/google/Protobuf ?

**Comment by kcleung** [comment]
My version of ubuntu is 16.04, and using cmake 3.5.1  So both ubuntu and cmake are new.  It just doesn't like the missing separator in:
CMakeFiles/libprotobuf-lite.dir/depend.make:4

I can't see relevant reports at Protobuf, which does not use cmake.

Have we copied their code into our repository and somehow converted it to cmake?

Also have anyone tried to compile Cura on Ubuntu 16.04?

**Comment by buaacarzp** [comment]
I meet this problem too, please help me ... my qq number is 510695983, thank you very much.
\

**Comment by Ghostkeeper** [comment]
That's weird, since this repository doesn't build Protobuf any more.
