### ISSUE TITLE
Cura on Ubuntu 14.04: unsatisfiable dependency: python3-pyqt5 (>=5.4.0)

### ISSUE THREAD

**Issue by TTN-** [Ultimaker/cura-build#6]
Hi,

I'm unable to install Cura 15.06 on Ubuntu 14.04 x64, the dependency python3-pyqt5 (>=5.4.0) is not satisfiable.

Is there planned support for Ubuntu 14.04?

**Comment by TTN-** [comment]
Attempting to build from source results in this:
```
Traceback (most recent call last):
  File "cura_app.py", line 6, in <module>
    import cura.CuraApplication 
  File "/home/jotham/Cura/cura/CuraApplication.py", line 4, in <module>
    from UM.Qt.QtApplication import QtApplication
  File "/usr/lib/python3.4/dist-packages/UM/Qt/QtApplication.py", line 32, in <module>
    raise UnsupportedVersionError("This application requires at least PyQt 5.4.0")
UM.Qt.QtApplication.UnsupportedVersionError: This application requires at least PyQt 5.4.0
```

**Comment by oliv3r** [comment]
While I can't speak for @awhiemstra I'm pretty sure we are not going to support a 1 1/2 year old ubuntu release, even though it is a LTS release. As can be seen in https://github.com/Ultimaker/Cura/issues/114 there are some bugs in pyqt5-5.2.1 that cause crashes. I belive that Ubuntu 15.04 does have the correct pyqt5 version, so upgrading Ubuntu to a more recent version is a possibility.

**Comment by awhiemstra** [comment]
We hard-require PyQt 5.4 due to known bugs with previous versions. I have plans to build an LTS package for 14.04 and Debian Jessie that includes all dependencies, but this does not have the highest priority at the moment.

**Comment by peteruithoven** [comment]
@oliv3r even though it's indeed old it is a version other distributions, like [Elementary OS](http://elementary.io/) are build on. I'm also looking for a solution, is there any way I can install PyQt5 on Ubuntu 14.04 / Elementary OS? 
I'm quite Python noob, I've checked if I could install it through pip, but it simply states `No distributions at all found for PyQt5`.
