### ISSUE TITLE
Building libArcus problem

### ISSUE THREAD

**Issue by caucycaucy** [Ultimaker/cura-build#62]
Hi All,

  My environment is: Win10+MSYS2+MinGW64+Python3.4.3. I've built the protobuf sucessfully. But when I built libArcus, there is an error related with SIP. So I download SIP 4.18 package, and extract it to "C:\msys32\usr\local\sip-4.18", 
Command "python configure.py --platform linux-g++" runs okay. But command "make" is failed,

ding@DZ MSYS /usr/local/sip-4.18
$ make
make[1]: Entering directory '/usr/local/sip-4.18/sipgen'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/sip-4.18/sipgen'
make[1]: Entering directory '/usr/local/sip-4.18/siplib'
g++ -shared -o sip.so siplib.o apiversions.o descriptors.o qtlib.o threads.o objmap.o voidptr.o array.o bool.o
siplib.o:siplib.c:(.text+0xa6): undefined reference to `_imp___Py_NoneStruct'
siplib.o:siplib.c:(.text+0x855): undefined reference to `_imp__PyType_Type'
siplib.o:siplib.c:(.text+0x914): undefined reference to `_imp__PyType_Type'
.....
  Any suggestion is welcome.
  Thanks in advance.

Ding

**Comment by Ghostkeeper** [comment]
You're getting a linking error. In my experience, those are usually caused by mixing multiple compilers. Since the linking error is a reference to a Python object (`None`), this might be one of those cases where you have to use the same compiler as CPython was compiled with. In your case that is Visual Studio 2010.

Don't go by my advice though. SIP has a mailinglist over at https://www.riverbankcomputing.com/mailman/listinfo/pyqt which might be of help.

**Comment by caucycaucy** [comment]
Hi Ghostkeeper,
 Really appreciate for your patience for my various stupid questions. Today, I tried to use the cura-build script to build whole cura in my Windows10. I strictly obey the building rules of cura-build, but finally I got an error. I think everything is okay now(protobuf, libArcus, curaengine.exe are built successfully using the script), but left this error.

[ 95%] Completed 'Cura-Doodle3D'
[100%] Built target Cura-Doodle3D
Running py2exe
Traceback (most recent call last):
  File "setup_win32.py", line 13, in <module>
    import Arcus
ImportError: No module named 'Arcus'
CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
mingw32-make[2]: *** [build_exe] Error 1 CMakeFiles\Makefile2:563: recipe for target 'CMakeFiles/build_exe.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Does anyone have this similar error?
Thanks in advance.

Ding

**Comment by sedwards2009** [comment]
I've got some improvements in the pipeline for the Arcus build system which should improve life on Windows.

**Comment by caucycaucy** [comment]
Hi sedwards2009,

  You mean you just commit some codes to improve the libArcus buiding? How should I do? Just run the following commands again?

REM 64-bit
git clone git@github.com:Ultimaker/cura-build.git
cd cura-build
mkdir build
cd build
..\env_win64.bat
cmake -G "MinGW Makefiles" -DBUILD_64BIT:BOOL=ON ..
mingw32-make
mingw32-make package

 Thanks.

Ding

**Comment by caucycaucy** [comment]
Hi sedwards2009,

  I just update and try it again, but it's still the same.
  Thanks.

Ding

**Comment by Ghostkeeper** [comment]
What I'd do is this:

1. Find a Python module called Arcus.a or Arcus.dll. It should be built by the time it gets to the py2exe step. It should be somewhere inside the .../inst folder inside cura-build.
2. In a command line, execute `SET PYTHONPATH=%PYTHONPATH%;<path to the folder that contains your Arcus.dll or Arcus.a file>`.
3. Run `mingw32-make package` again.

**Comment by caucycaucy** [comment]
Hi Ghostkeeper,

  Thanks for your help, but it doesn't work for me.
  Thanks again.

Ding

**Comment by Ghostkeeper** [comment]
Getting the same error?

**Comment by caucycaucy** [comment]
Hi Ghostkeeper,

  We finally build cura successfully. The new version is really cool. Thanks for your help. 
  The key is to build protobuf, libArcus and sip manually using CMake, nmake and VS2015, and copy one extra dll to dist directory.  
  Anyway, thank you very much for your patience.

Ding

**Comment by jiangkuncom** [comment]
hi,i am a newer ,how should i use the cura build to build cura? my os is win10 ,how can i do on my sys,one by one step?thanks very much

**Comment by Ghostkeeper** [comment]
There are some instructions for Windows on the front page of this repository: https://github.com/Ultimaker/cura-build#windows
