### ISSUE TITLE
ImportError: No module named 'Arcus'

### ISSUE THREAD

**Issue by kenjo** [Ultimaker/cura-build#81]
why ? 

```
An uncaught exception has occurred!
Traceback (most recent call last):
  File "/opt/cura/bin/cura", line 47, in <module>
    import Arcus #@UnusedImport
ImportError: No module named 'Arcus'
```

---

```
dpkg -L cura | grep -i arcus
/opt/cura/lib/cmake/Arcus
/opt/cura/lib/cmake/Arcus/Arcus-targets-noconfig.cmake
/opt/cura/lib/cmake/Arcus/Arcus-targets.cmake
/opt/cura/lib/cmake/Arcus/ArcusConfig.cmake
/opt/cura/lib/cmake/Arcus/ArcusConfigVersion.cmake
/opt/cura/lib/libArcus.a
/opt/cura/lib/python3.5/site-packages/Arcus.so

```

the /opt/cura/lib/libArcus.a probably should not even be in the install but should there not be a python module ?? now we only have a Arcus.so file. 

I tried 

`cp -r ./Arcus-prefix/src/Arcus/python/Arcus /opt/cura/lib/python3/dist-packages/
`
but then I get this

```
An uncaught exception has occurred!
Traceback (most recent call last):
  File "/opt/cura/bin/cura", line 49, in <module>
    import cura.CuraApplication
  File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 4, in <module>
    from UM.Qt.QtApplication import QtApplication
  File "/opt/cura/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 17, in <module>
    from UM.Qt.Bindings.Bindings import Bindings
  File "/opt/cura/lib/python3/dist-packages/UM/Qt/Bindings/Bindings.py", line 13, in <module>
    from . import BackendProxy
  File "/opt/cura/lib/python3/dist-packages/UM/Qt/Bindings/BackendProxy.py", line 9, in <module>
    from UM.Backend.Backend import BackendState
  File "/opt/cura/lib/python3/dist-packages/UM/Backend/Backend.py", line 6, in <module>
    from UM.Backend.SignalSocket import SignalSocket
  File "/opt/cura/lib/python3/dist-packages/UM/Backend/SignalSocket.py", line 34, in <module>
    class _SocketListener(Arcus.SocketListener):
AttributeError: module 'Arcus' has no attribute 'SocketListener'


```

**Comment by Ghostkeeper** [comment]
> but should there not be a python module ?? now we only have a Arcus.so file.

The Arcus.so file _is_ the Python package. Right?

One discrepancy I see is that it seems to run Cura from /opt/cura/lib/python3 but install Arcus.so to /opt/cura/lib/python3**.5**. Perhaps it is using the wrong Python version on your computer?

**Comment by kenjo** [comment]
Turns out that if I do 
`cp /opt/cura/lib/python3.5/site-packages/Arcus.so /opt/cura/lib/python3/dist-packages/
`
then the module is found and cura starts. 
well it do not actually work as I get a segmentation fault before the program opens up a window.

`/usr/bin/cura: line 3: 29869 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/opt/cura/lib PYTHONPATH=/opt/cura/lib/python3/dist-packages QT_PLUGIN_PATH=/opt/cura/lib/plugins QML2_IMPORT_PATH=/opt/cura/lib/qml QT_QPA_FONTDIR=/opt/cura/lib/fonts python3.5 /opt/cura/bin/cura "$@"
`

**Comment by thopiekar** [comment]
No, there are two Arcus.so's.

One of them is the Python module and the other is a C/C++ library.
You probably need to use a CMake option to (forcibly?) enable the build of a Python module.

Just take a look at the build log of my libArcus packages for my PPA. As you can see two Arcus.so files.
And as you've noticed a 'C/C++ library' != 'Python module' :wink:

**Comment by kenjo** [comment]
No there is only the python module it is statically linked so no sharde c lib included.

The problem was that it was in a new location. I looked at a previous build I had and then it was installed into /opt/cura/lib/python3/dist-packages/ and when I moved it the module was found.

Not sure why the install location has changed.

And by the way your ppa did not produce any output at all for me no errors no nothing when i run cura. I'm on Yakkety Yak.

**Comment by thopiekar** [comment]
Don't understand what you are doing there, but don't mix both installations.

Cura by Ultimaker is something like a portable Version on Windows. It's a bundle and comes with almost every dependency.

My PPA uses almost every dependency provided by Ubuntu (at least whenever possible).
So if you decide to use my PPA make sure you are using all packages from my PPA and remove every manually installed files.
That's why I've made these packages: keeping the installation of Cura lightweight and clean.
(However, Ultimaker gives support and guarantees on their bundle.)

So if you are using my PPA there should be no /opt/cura. And be sure if you mix packages, it is up to you to get that working 😉

**Comment by kenjo** [comment]
Well I was running your ppa before I build with cura-build scripts. the cura from ultimaker and cura-build installs in /opt and nowhere else well /usr/bin/cura is same but there is nothing that can get in the way when running your ppa.

the one from ultimaker still has a dependency on python 3.4 that is not available on Yakkety Yak. that package still installs so they have some issue with the dependency being wrong as it can't actually run.

So I tried your ppa again. same thing no output. also I did not get the correct cura-engine. but we should move that issue to launchpad I guess. How do I report a bug against your package ??

```
kenjo@brix:/mnt/data/cura-build/build$ dpkg -l "*cura*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  cura                                          1:2.1.2-0+master~2016081517 all                         3D printer / slicing GUI built on top of the Uranium framework
ii  cura-engine                                   14.01-2                     amd64                       commandline slicer program for 3-D printers

```
dpkg -S /usr/bin/cura
cura: /usr/bin/cura

**Comment by thopiekar** [comment]
I hope you mean Xenial. Yakkety is currently in development and I even don't jump into it because they (Canonical) are planing to move to a newer Qt5 release, which causes problems as I read on the internet.
In short: It is possible that you'll see problems which don't occur for me.

Ok, just run "cura" in the terminal and there should be an output.. really..

**Comment by thopiekar** [comment]
You should have asked me earlier via mail about help. Someone just mailed my an hour ago and we've found two packages which were missing. You are probably getting the same problem if you are using Ubuntu Mate where a great set of QML modules are not preinstalled.

**Comment by kenjo** [comment]
I'm not running mate. 

If I start it in the debugger I get this. 
```
pdb3.5 /usr/bin/cura 
> /usr/bin/cura(6)<module>()
-> import os
(Pdb) c
Traceback (most recent call last):
  File "/usr/lib/python3.5/pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/bin/cura", line 6, in <module>
    import os
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 21, in <module>
    from UM.Settings.Validator import Validator
ImportError: No module named 'UM.Settings.Validator'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3/dist-packages/cura/CuraApplication.py(21)<module>()
-> from UM.Settings.Validator import Validator

```

**Comment by thopiekar** [comment]
You are using my [master] PPA while having Uranium installed from [2.1] PPA :exclamation: 
https://github.com/Ultimaker/Uranium/blob/2.1/UM/Settings/Validator.py
As you can see there is no UM.Settings.Validator in Uranium 2.1.

**Comment by kenjo** [comment]
Right I upgraded usually all ppa repos is removed but now I have both the old and the new active ??? ok that explains a lot. and it was not the only one. I need to clean up this mess.

**Comment by thopiekar** [comment]
After that it should really work :ok_hand: 

(Good night :wink: )

**Comment by kenjo** [comment]
Now the ppa version started.
