### ISSUE TITLE
Virtual Machine with configured build environment

### ISSUE THREAD

**Issue by michalplatek** [Ultimaker/cura-build#86]
I would like to be able to build Cura 2.1 without tons and tons of errors.
Can I request a Virtual Machine image (eg. for VirtualBox) that contains buildable Cura?

**Comment by sedwards2009** [comment]
Which operating system did you have in mind?

**Comment by filipgoc** [comment]
I LOVE this idea. 
5 thumbs up. 

Any linux based environment would be great for VM. Debian, Ubuntu, Mint... Anything goes. 
Would greatly simplify building Cura from scratch.

**Comment by Ghostkeeper** [comment]
@awhiemstra was recently working on a Puppet configuration to make it easy to get a build server running. I think it was using CentOS.

**Comment by Bostwickenator** [comment]
Has any progress been made on this. I sunk two hours into trying to setup Ubuntu for builds and just ended up giving up when I hit sip errors.

**Comment by Ghostkeeper** [comment]
Progress has been made on this but it's still in the testing phase.

**Comment by filipgoc** [comment]
When this is done, it will be CHRISTMAS without overstating it. (I think I tried and failed to compile Cura four times now... and then I realize I need to compile for each system separately...)

**Comment by LipuFei** [comment]
You can check https://github.com/Ultimaker/cura-build-environment/pull/71 and https://github.com/Ultimaker/cura-build/pull/223, with which you create Cura builds using docker on Linux and Windows. This will greatly simplify the effort spent on creating your build infrastructure. You basically only need to have `git` and `docker-ce` installed on your build machines.
